//! Execution agent for running workflow steps
//!
//! Phase 2 of the two-phase workflow execution model.
//! Spawns Claude with step's configured agents/skills to execute
//! the prompt generated by the orchestrator.

use chrono::Utc;
use std::sync::Arc;
use tauri::{AppHandle, Emitter};
use tokio::io::{AsyncBufReadExt, BufReader};
use tokio::process::Command;
use vertebrae_core::{ExecutionService, OrchestratorOutput, PermissionMode, SessionLog};

use crate::events::{WorkflowExecutionEvent, WorkflowExecutionEventType};

use super::helpers::find_claude_binary;
use super::logging::{append_to_workflow_log, trace};

/// Run execution agent with the generated prompt
///
/// Spawns Claude with step's configured agents/skills and --dangerously-skip-permissions
/// to execute the prompt generated by the orchestrator.
///
/// The executor is blocked from running vtb workflow transition commands - the workflow
/// runner controls all step transitions.
pub async fn run_execution(
    step: &vertebrae_core::Step,
    exec_id: &str,
    task_id: &str,
    workflow_id: &str,
    orchestrator_output: &OrchestratorOutput,
    executions: &Arc<dyn ExecutionService>,
    app_handle: &AppHandle,
) -> Result<(), String> {
    trace(
        task_id,
        &format!("[exec_id={}] >>> run_execution ENTERED", exec_id),
    );

    log::info!(
        "[WorkflowRunner] Phase 2: Running execution for step: {}",
        step.name
    );

    // 1. Emit step started event
    let _ = app_handle.emit(
        "workflow-execution-event",
        &WorkflowExecutionEvent {
            task_id: task_id.to_string(),
            workflow_id: workflow_id.to_string(),
            event_type: WorkflowExecutionEventType::StepStarted {
                execution_id: exec_id.to_string(),
                step_name: step.name.clone(),
            },
        },
    );

    // 2. Find Claude binary
    let claude_path = find_claude_binary()?;

    // 3. Build execution command with step's agents/skills
    let mut cmd = Command::new(&claude_path);

    // Use step's agent_config if non-empty, otherwise use step's agents/skills
    let mut agent_config = if !step.agent_config.is_empty() {
        step.agent_config.clone()
    } else {
        // Build config from step's agents and skills
        let mut config = vertebrae_core::AgentConfig::new();

        // For now, use the step's goal as an append system prompt if available
        if let Some(ref goal) = step.goal {
            config = config.with_append_system_prompt(format!(
                "Step goal: {}\n\nYou are working on step '{}' of the workflow.",
                goal, step.name
            ));
        }

        config
    };

    // Block executor from running workflow transition commands
    // The workflow runner controls all step transitions
    agent_config = agent_config.with_disallowed_tools(vec![
        "Bash(vtb workflow advance*)".to_string(),
        "Bash(vtb workflow retreat*)".to_string(),
        "Bash(vtb transition-to*)".to_string(),
    ]);

    // Add agent config args
    for arg in agent_config.to_cli_args() {
        cmd.arg(arg);
    }

    // Add step's agent files as --agent arguments
    for agent_path in &step.agents {
        cmd.arg("--agent");
        cmd.arg(agent_path);
    }

    // Add --permission-mode bypass for vtb read commands to work
    cmd.arg("--permission-mode");
    cmd.arg(PermissionMode::BypassPermissions.as_str());

    // Build the execution prompt from orchestrator output
    let execution_prompt = orchestrator_output.to_execution_prompt();

    // Augment with step goal to ensure executor sees required commands
    // The step goal contains explicit vtb command syntax that orchestrator may omit
    let execution_prompt = if let Some(ref goal) = step.goal {
        format!(
            r#"{execution_prompt}

---

## Step Requirements (from workflow definition)

{goal}

You MUST follow these requirements exactly. Use the specified commands - do NOT create markdown files or use alternative approaches."#
        )
    } else {
        execution_prompt
    };

    // Log the execution prompt for debugging
    log::info!(
        "[WorkflowRunner] Phase 2 execution prompt:\n{}",
        execution_prompt
    );

    // Add execution prompt
    cmd.arg("--print");
    cmd.arg(&execution_prompt);

    cmd.arg("--output-format");
    cmd.arg("stream-json");

    // Set up pipes
    cmd.stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped());

    // 4. Spawn and stream output
    trace(
        task_id,
        &format!("[exec_id={}] Spawning execution agent process...", exec_id),
    );
    let mut child = match cmd.spawn() {
        Ok(c) => {
            trace(
                task_id,
                &format!(
                    "[exec_id={}] Execution agent process spawned successfully",
                    exec_id
                ),
            );
            c
        }
        Err(e) => {
            let err = format!("Failed to spawn execution agent: {}", e);
            trace(task_id, &format!("[exec_id={}] ERROR: {}", exec_id, err));
            return Err(err);
        }
    };

    let stdout = match child.stdout.take() {
        Some(s) => s,
        None => {
            let err = "Failed to get stdout".to_string();
            trace(task_id, &format!("[exec_id={}] ERROR: {}", exec_id, err));
            return Err(err);
        }
    };

    let mut reader = BufReader::new(stdout);
    let mut line = String::new();
    let mut output_batch = Vec::new();
    let mut full_output = String::new();

    trace(
        task_id,
        &format!(
            "[exec_id={}] Reading execution output (streaming)...",
            exec_id
        ),
    );
    log::info!("[WorkflowRunner] Started reading execution output");

    loop {
        match reader.read_line(&mut line).await {
            Ok(0) => break, // EOF
            Ok(_) => {
                full_output.push_str(&line);
                output_batch.push(line.trim().to_string());

                // Stream each line to the log file in real-time
                let _ = append_to_workflow_log(task_id, "EXECUTOR", line.trim());

                // Emit and save batches of 100 lines
                if output_batch.len() >= 100 {
                    log::debug!(
                        "[WorkflowRunner] Emitting and saving batch of {} lines",
                        output_batch.len()
                    );

                    // Emit progress event
                    let _ = app_handle.emit(
                        "workflow-execution-event",
                        &WorkflowExecutionEvent {
                            task_id: task_id.to_string(),
                            workflow_id: workflow_id.to_string(),
                            event_type: WorkflowExecutionEventType::StepProgress {
                                execution_id: exec_id.to_string(),
                                output_lines: output_batch.clone(),
                            },
                        },
                    );

                    // Save to database
                    for output_line in &output_batch {
                        let log_entry = SessionLog {
                            id: None,
                            step_execution_id: exec_id.to_string(),
                            content: output_line.clone(),
                            created_at: Utc::now(),
                        };
                        let _ = executions.add_log(log_entry).await;
                    }

                    output_batch.clear();
                }

                line.clear();
            }
            Err(e) => {
                let err = format!("Failed to read line: {}", e);
                trace(task_id, &format!("[exec_id={}] ERROR: {}", exec_id, err));
                return Err(err);
            }
        }
    }

    trace(
        task_id,
        &format!(
            "[exec_id={}] Execution output complete ({} bytes)",
            exec_id,
            full_output.len()
        ),
    );

    // Emit remaining output
    if !output_batch.is_empty() {
        log::debug!(
            "[WorkflowRunner] Emitting and saving final batch of {} lines",
            output_batch.len()
        );

        let _ = app_handle.emit(
            "workflow-execution-event",
            &WorkflowExecutionEvent {
                task_id: task_id.to_string(),
                workflow_id: workflow_id.to_string(),
                event_type: WorkflowExecutionEventType::StepProgress {
                    execution_id: exec_id.to_string(),
                    output_lines: output_batch.clone(),
                },
            },
        );

        for output_line in output_batch {
            let log_entry = SessionLog {
                id: None,
                step_execution_id: exec_id.to_string(),
                content: output_line,
                created_at: Utc::now(),
            };
            let _ = executions.add_log(log_entry).await;
        }
    }

    // Append executor output to log file for tailing
    let _ = append_to_workflow_log(task_id, "EXECUTOR", &full_output);

    // 5. Wait for completion
    trace(
        task_id,
        &format!(
            "[exec_id={}] Waiting for execution agent process to exit...",
            exec_id
        ),
    );
    let status = match child.wait().await {
        Ok(s) => {
            trace(
                task_id,
                &format!(
                    "[exec_id={}] Execution agent process exited with status: {:?}",
                    exec_id, s
                ),
            );
            s
        }
        Err(e) => {
            let err = format!("Failed to wait: {}", e);
            trace(task_id, &format!("[exec_id={}] ERROR: {}", exec_id, err));
            return Err(err);
        }
    };

    if status.success() {
        trace(
            task_id,
            &format!("[exec_id={}] Execution agent exited successfully", exec_id),
        );
        log::info!("[WorkflowRunner] Execution completed successfully");

        // Update execution output (status update handled by caller)
        trace(
            task_id,
            &format!(
                "[exec_id={}] Updating execution record with output...",
                exec_id
            ),
        );
        match executions
            .update_execution(exec_id, Some(full_output), None)
            .await
        {
            Ok(()) => {
                trace(
                    task_id,
                    &format!(
                        "[exec_id={}] Execution record updated successfully",
                        exec_id
                    ),
                );
            }
            Err(e) => {
                let err = format!("Failed to update execution: {}", e);
                trace(task_id, &format!("[exec_id={}] ERROR: {}", exec_id, err));
                return Err(err);
            }
        }

        trace(
            task_id,
            &format!("[exec_id={}] <<< run_execution RETURNING Ok", exec_id),
        );
        Ok(())
    } else {
        let error = format!(
            "Execution exited with code: {}",
            status.code().unwrap_or(-1)
        );
        trace(task_id, &format!("[exec_id={}] ERROR: {}", exec_id, error));
        log::error!("[WorkflowRunner] {}", error);

        trace(
            task_id,
            &format!(
                "[exec_id={}] <<< run_execution RETURNING Err (non-zero exit)",
                exec_id
            ),
        );
        Err(error)
    }
}
