//! Execution agent for running workflow steps
//!
//! Phase 2 of the two-phase workflow execution model.
//! Spawns Claude with step's configured agents/skills to execute
//! the prompt generated by the orchestrator.

use chrono::Utc;
use std::sync::Arc;
use vertebrae_core::{ExecutionService, OrchestratorOutput, SessionLog};

use super::args::build_executor_args;
use super::command_runner::CommandRunner;
use super::logging::trace;

/// Execution logic that accepts a `CommandRunner`.
///
/// Builds CLI args, runs the process, saves session logs, and updates the
/// execution record. Event emission is handled by the caller (step.rs).
pub(crate) async fn run_execution_with(
    runner: &dyn CommandRunner,
    step: &vertebrae_core::Step,
    exec_id: &str,
    task_id: &str,
    _workflow_id: &str,
    orchestrator_output: &OrchestratorOutput,
    executions: &Arc<dyn ExecutionService>,
) -> Result<(), String> {
    trace(
        task_id,
        &format!("[exec_id={}] >>> run_execution_with ENTERED", exec_id),
    );

    log::info!(
        "[WorkflowRunner] Phase 2: Running execution for step: {}",
        step.name
    );

    // Build args
    let (claude_path, args) = build_executor_args(step, orchestrator_output)?;

    // Run the process
    let process_output = runner.run(&claude_path, &args).await?;

    trace(
        task_id,
        &format!(
            "[exec_id={}] Execution output complete ({} bytes)",
            exec_id,
            process_output.stdout.len()
        ),
    );

    // Save output lines as SessionLog entries
    let lines: Vec<String> = process_output
        .stdout
        .lines()
        .map(|l| l.trim().to_string())
        .collect();

    for line in &lines {
        let log_entry = SessionLog {
            id: None,
            step_execution_id: exec_id.to_string(),
            content: line.clone(),
            created_at: Utc::now(),
        };
        let _ = executions.add_log(log_entry).await;
    }

    if process_output.success {
        trace(
            task_id,
            &format!("[exec_id={}] Execution agent exited successfully", exec_id),
        );
        log::info!("[WorkflowRunner] Execution completed successfully");

        // Update execution output (status update handled by caller)
        executions
            .update_execution(exec_id, Some(process_output.stdout), None)
            .await
            .map_err(|e| format!("Failed to update execution: {}", e))?;

        trace(
            task_id,
            &format!("[exec_id={}] <<< run_execution_with RETURNING Ok", exec_id),
        );
        Ok(())
    } else {
        let error = format!(
            "Execution exited with code: {}",
            process_output.exit_code.unwrap_or(-1)
        );
        trace(task_id, &format!("[exec_id={}] ERROR: {}", exec_id, error));
        log::error!("[WorkflowRunner] {}", error);
        Err(error)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mock::mock_services;
    use crate::workflow_runner::command_runner::{MockCommandRunner, ProcessOutput};
    use vertebrae_core::{ExecutionStatus, OrchestratorOutput, Step, StepExecution};

    async fn setup_execution(executions: &Arc<dyn ExecutionService>) -> String {
        let exec = StepExecution {
            id: None,
            task_id: "task1".to_string(),
            workflow_id: "wf1".to_string(),
            step_name: "test-step".to_string(),
            started_at: chrono::Utc::now(),
            completed_at: None,
            status: ExecutionStatus::InProgress,
            context: None,
            prompt: None,
            output: None,
            transition_result: None,
            model_used: Some("haiku".to_string()),
            session_id: None,
            token_usage: None,
            cost_usd: None,
            duration_ms: None,
        };
        executions.create_execution(exec).await.unwrap()
    }

    #[tokio::test]
    async fn success_saves_logs_and_updates_execution() {
        let services = mock_services();
        let executions = services.executions_arc();
        let exec_id = setup_execution(&executions).await;

        let runner = MockCommandRunner::new(vec![Ok(ProcessOutput {
            stdout: "line1\nline2\nline3\n".to_string(),
            success: true,
            exit_code: Some(0),
        })]);

        let step = Step::new("test-step", "wf1");
        let orch_output = OrchestratorOutput::new("do the thing");

        let result = run_execution_with(
            &runner,
            &step,
            &exec_id,
            "task1",
            "wf1",
            &orch_output,
            &executions,
        )
        .await;

        assert!(result.is_ok());

        // Verify logs were saved
        let logs = executions.list_logs_for_execution(&exec_id).await.unwrap();
        assert_eq!(logs.len(), 3);
        assert_eq!(logs[0].content, "line1");
        assert_eq!(logs[1].content, "line2");
        assert_eq!(logs[2].content, "line3");

        // Verify execution record was updated
        let exec = executions.get_execution(&exec_id).await.unwrap().unwrap();
        assert!(exec.output.is_some());
    }

    #[tokio::test]
    async fn failure_non_zero_exit_propagates_error() {
        let services = mock_services();
        let executions = services.executions_arc();
        let exec_id = setup_execution(&executions).await;

        let runner = MockCommandRunner::new(vec![Ok(ProcessOutput {
            stdout: "some output\n".to_string(),
            success: false,
            exit_code: Some(1),
        })]);

        let step = Step::new("test-step", "wf1");
        let orch_output = OrchestratorOutput::new("do the thing");

        let result = run_execution_with(
            &runner,
            &step,
            &exec_id,
            "task1",
            "wf1",
            &orch_output,
            &executions,
        )
        .await;

        assert!(result.is_err());
        assert!(result.unwrap_err().contains("exited with code: 1"));
    }

    #[tokio::test]
    async fn many_lines_saved_correctly() {
        let services = mock_services();
        let executions = services.executions_arc();
        let exec_id = setup_execution(&executions).await;

        // Generate 250 lines
        let lines: String = (0..250).map(|i| format!("line{}\n", i)).collect();

        let runner = MockCommandRunner::new(vec![Ok(ProcessOutput {
            stdout: lines,
            success: true,
            exit_code: Some(0),
        })]);

        let step = Step::new("test-step", "wf1");
        let orch_output = OrchestratorOutput::new("do the thing");

        run_execution_with(
            &runner,
            &step,
            &exec_id,
            "task1",
            "wf1",
            &orch_output,
            &executions,
        )
        .await
        .unwrap();

        let logs = executions.list_logs_for_execution(&exec_id).await.unwrap();
        assert_eq!(logs.len(), 250);
    }

    #[tokio::test]
    async fn execution_record_updated_with_full_output() {
        let services = mock_services();
        let executions = services.executions_arc();
        let exec_id = setup_execution(&executions).await;

        let stdout = "output data\n".to_string();
        let runner = MockCommandRunner::new(vec![Ok(ProcessOutput {
            stdout: stdout.clone(),
            success: true,
            exit_code: Some(0),
        })]);

        let step = Step::new("test-step", "wf1");
        let orch_output = OrchestratorOutput::new("do the thing");

        run_execution_with(
            &runner,
            &step,
            &exec_id,
            "task1",
            "wf1",
            &orch_output,
            &executions,
        )
        .await
        .unwrap();

        let exec = executions.get_execution(&exec_id).await.unwrap().unwrap();
        assert_eq!(exec.output, Some(stdout));
    }
}
