#![allow(deprecated)]

pub mod commands;
pub mod events;
pub mod project_config;
pub mod pty_manager;
pub mod sacrum;
pub mod types;
pub mod websocket_client;
pub mod workflow_runner;

#[cfg(test)]
pub mod mock;

use std::sync::Arc;
use tokio::sync::RwLock;

use specta_typescript::Typescript;
use tauri::Manager;
use tauri_specta::{collect_commands, collect_events, Builder};
use vertebrae_sacrum_client::{SacrumClient, SacrumConfig};

use commands::AppState;
use events::{
    StepChangedEvent, StepExecutionChangedEvent, TaskChangedEvent, TaskStepChangedEvent,
    WorkflowChangedEvent, WorkflowExecutionEvent,
};
use project_config::ProjectConfig;
use pty_manager::{PtyExitEvent, PtyManager, PtyOutputEvent};

/// Example command that will be exported with type definitions.
/// This serves as a template for future Tauri commands.
#[tauri::command]
#[specta::specta]
fn greet(name: String) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

/// Export TypeScript bindings to the frontend src directory.
/// This function is called by the generate-types binary.
pub fn export_bindings() -> Result<(), Box<dyn std::error::Error>> {
    let builder = create_builder();
    builder.export(
        Typescript::default()
            .header("/* eslint-disable */\n// @ts-nocheck\n// This file was auto-generated by tauri-specta. Do not edit."),
        "../src/bindings.ts",
    )?;
    Ok(())
}

/// Create the tauri-specta builder with all commands and events registered.
fn create_builder() -> Builder {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            greet,
            // Project management commands
            commands::get_projects,
            commands::add_project,
            commands::remove_project,
            commands::get_current_project,
            commands::set_current_project,
            commands::has_project_selected,
            // Task commands
            commands::list_tasks,
            commands::get_task,
            // Task relationship commands
            commands::set_parent,
            commands::remove_parent,
            commands::add_dependency,
            commands::remove_dependency,
            // Task mutation commands
            commands::create_task,
            commands::update_task,
            commands::assign_workflow,
            // Task deletion command
            commands::delete_task,
            // Section mutation commands
            commands::add_section,
            commands::edit_section,
            commands::mark_section_done,
            commands::remove_section,
            commands::add_criterion_ref,
            // Code reference commands
            commands::add_code_ref,
            commands::remove_code_refs,
            commands::replace_code_refs,
            // Workflow commands
            commands::list_workflows,
            commands::get_workflow,
            commands::get_workflow_with_tasks,
            commands::get_workflow_with_task_details,
            commands::get_pipeline_data,
            commands::list_workflow_transitions,
            // Execution commands
            commands::get_task_executions,
            commands::get_execution_logs,
            // Step commands (first-class workflow steps)
            commands::list_steps_for_workflow,
            commands::get_step,
            commands::create_step,
            commands::update_step,
            commands::delete_step,
            // Workflow execution commands
            commands::run_workflow,
            // PTY commands
            commands::create_pty_session,
            commands::write_pty,
            commands::resize_pty,
            commands::close_pty_session,
        ])
        .events(collect_events![
            TaskChangedEvent,
            TaskStepChangedEvent,
            WorkflowChangedEvent,
            StepChangedEvent,
            StepExecutionChangedEvent,
            WorkflowExecutionEvent,
            PtyOutputEvent,
            PtyExitEvent
        ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = create_builder();

    let mut tauri_app_builder = tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_window_state::Builder::new().build());

    if cfg!(debug_assertions) {
        tauri_app_builder = tauri_app_builder.plugin(
            tauri_plugin_log::Builder::default()
                .level(log::LevelFilter::Info)
                .build(),
        );
    }

    tauri_app_builder
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);

            // Initialize project configuration
            let project_config = ProjectConfig::new().expect("Failed to initialize project config");

            // Check if there's a current project selected (stored as slug)
            let current_project_slug = project_config.get_current_project();
            let service = if let Some(slug) = current_project_slug.clone() {
                log::info!(
                    "Attempting to connect to Sacrum backend for project: {}",
                    slug
                );

                tauri::async_runtime::block_on(async {
                    match SacrumConfig::load(&slug) {
                        Ok(config) => {
                            let client = SacrumClient::new(config);
                            let client_arc = Arc::new(client);
                            Some(crate::sacrum::from_sacrum(client_arc))
                        }
                        Err(e) => {
                            log::error!("Failed to load Sacrum configuration: {}", e);
                            None
                        }
                    }
                })
            } else {
                log::info!("No project selected, starting without Sacrum connection");
                None
            };

            // Manage application state with optional services
            app.manage(AppState {
                services: RwLock::new(service),
                project_config,
            });

            // Initialize PTY manager for terminal sessions
            app.manage(PtyManager::new());
            log::info!("[STARTUP] PTY manager initialized");

            // Start WebSocket connection to Sacrum for real-time updates
            let ws_slug = app.state::<AppState>().project_config.get_current_project();
            if let Some(slug) = ws_slug {
                if let Ok(config) = SacrumConfig::load(&slug) {
                    log::info!("[STARTUP] Starting WebSocket connection to Sacrum");
                    let socket = websocket_client::SacrumSocket::new(
                        config.base_url.clone(),
                        config.api_token.clone(),
                        config.project_id.clone(),
                    );
                    socket.connect(app.handle());
                    // Keep socket alive by storing it in app state
                    app.manage(socket);
                } else {
                    log::warn!(
                        "[STARTUP] Failed to load Sacrum config, WebSocket connection skipped"
                    );
                }
            } else {
                log::warn!("[STARTUP] No project slug available, WebSocket connection skipped");
            }

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
