pub mod commands;
pub mod events;
pub mod types;

use std::path::PathBuf;

use specta_typescript::Typescript;
use tauri::Manager;
use tauri_specta::{collect_commands, collect_events, Builder};
use vertebrae_db::Database;

use commands::AppState;
use events::{TaskChangedEvent, WorkflowChangedEvent};

/// Environment variable for database path override
const VTB_DB_PATH_ENV: &str = "VTB_DB_PATH";

/// Resolve database path using same logic as CLI
fn resolve_db_path() -> PathBuf {
    // Check environment variable first
    if let Ok(env_path) = std::env::var(VTB_DB_PATH_ENV) {
        if !env_path.is_empty() {
            return PathBuf::from(env_path);
        }
    }

    // Use default path (~/.vtb/data)
    Database::default_path().unwrap_or_else(|_| PathBuf::from(".vtb/data"))
}

/// Example command that will be exported with type definitions.
/// This serves as a template for future Tauri commands.
#[tauri::command]
#[specta::specta]
fn greet(name: String) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

/// Export TypeScript bindings to the frontend src directory.
/// This function is called by the generate-types binary.
pub fn export_bindings() -> Result<(), Box<dyn std::error::Error>> {
    let builder = create_builder();
    builder.export(
        Typescript::default()
            .header("/* eslint-disable */\n// @ts-nocheck\n// This file was auto-generated by tauri-specta. Do not edit."),
        "../src/bindings.ts",
    )?;
    Ok(())
}

/// Create the tauri-specta builder with all commands and events registered.
fn create_builder() -> Builder {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            greet,
            commands::list_tasks,
            commands::get_task,
            commands::get_task_hierarchy,
            commands::list_workflows,
            commands::get_workflow,
            commands::get_workflow_with_tasks,
        ])
        .events(collect_events![TaskChangedEvent, WorkflowChangedEvent])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = create_builder();

    tauri::Builder::default()
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);

            // Initialize database connection using Tauri's async runtime
            let db_path = resolve_db_path();
            log::info!("Connecting to database at: {:?}", db_path);

            let db = tauri::async_runtime::block_on(async {
                let db = Database::connect(&db_path)
                    .await
                    .expect("Failed to connect to database");
                db.init().await.expect("Failed to initialize database");
                db
            });

            // Manage application state with database
            app.manage(AppState { db });

            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
