pub mod commands;
pub mod events;
pub mod live_queries;
pub mod project_config;
pub mod types;

use std::path::PathBuf;
use tokio::sync::RwLock;

use specta_typescript::Typescript;
use tauri::Manager;
use tauri_specta::{collect_commands, collect_events, Builder};
use vertebrae_core::DefaultTaskService;
use vertebrae_db::Database;

use commands::AppState;
use events::{TaskChangedEvent, WorkflowChangedEvent};
use project_config::ProjectConfig;

/// Example command that will be exported with type definitions.
/// This serves as a template for future Tauri commands.
#[tauri::command]
#[specta::specta]
fn greet(name: String) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

/// Export TypeScript bindings to the frontend src directory.
/// This function is called by the generate-types binary.
pub fn export_bindings() -> Result<(), Box<dyn std::error::Error>> {
    let builder = create_builder();
    builder.export(
        Typescript::default()
            .header("/* eslint-disable */\n// @ts-nocheck\n// This file was auto-generated by tauri-specta. Do not edit."),
        "../src/bindings.ts",
    )?;
    Ok(())
}

/// Create the tauri-specta builder with all commands and events registered.
fn create_builder() -> Builder {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            greet,
            // Project management commands
            commands::get_projects,
            commands::add_project,
            commands::remove_project,
            commands::get_current_project,
            commands::set_current_project,
            commands::has_project_selected,
            // Task commands
            commands::list_tasks,
            commands::get_task,
            commands::get_task_hierarchy,
            // Workflow commands
            commands::list_workflows,
            commands::get_workflow,
            commands::get_workflow_with_tasks,
            // Execution commands
            commands::get_task_executions,
            commands::get_execution_logs,
        ])
        .events(collect_events![TaskChangedEvent, WorkflowChangedEvent])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = create_builder();

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);

            // Initialize project configuration
            let project_config = ProjectConfig::new().expect("Failed to initialize project config");

            // Check if there's a current project set
            let current_project = project_config.get_current_project();
            let (service, live_registry) = if let Some(ref project_path) = current_project {
                let db_path = PathBuf::from(project_path).join(".vtb/data");
                log::info!("Connecting to database at: {:?}", db_path);

                let app_handle = app.handle().clone();

                tauri::async_runtime::block_on(async {
                    match Database::connect(&db_path).await {
                        Ok(db) => {
                            if let Err(e) = db.init().await {
                                log::error!("Failed to initialize database: {}", e);
                                (None, live_queries::LiveQueryRegistry::new())
                            } else {
                                // Clone the database client for LIVE queries
                                let client = db.client().clone();

                                // Start LIVE query for task table changes
                                let mut registry = live_queries::LiveQueryRegistry::new();
                                if let Err(e) =
                                    registry.start_task_live_query(client, app_handle).await
                                {
                                    log::error!("Failed to start task LIVE query: {}", e);
                                    log::info!("App will continue with polling fallback");
                                }

                                (Some(DefaultTaskService::new(db)), registry)
                            }
                        }
                        Err(e) => {
                            log::error!("Failed to connect to database: {}", e);
                            (None, live_queries::LiveQueryRegistry::new())
                        }
                    }
                })
            } else {
                log::info!("No project selected, starting without database connection");
                (None, live_queries::LiveQueryRegistry::new())
            };

            // Manage application state with optional task service
            app.manage(AppState {
                service: RwLock::new(service),
                project_config,
            });

            // Store LIVE query registry to keep streams alive for app lifetime
            app.manage(RwLock::new(live_registry));

            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
