/* eslint-disable */
// @ts-nocheck
// This file was auto-generated by tauri-specta. Do not edit.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Example command that will be exported with type definitions.
 * This serves as a template for future Tauri commands.
 */
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
/**
 * Get the list of saved projects
 */
async getProjects() : Promise<Result<SavedProject[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a project to the saved list
 * 
 * Takes a directory path, derives a slug from the folder name,
 * creates the project in Sacrum API if needed, and saves to config.toml.
 */
async addProject(path: string) : Promise<Result<SavedProject, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a project from the saved list
 * 
 * Removes the project from config.toml by slug. If the removed project
 * is the currently selected project, clears the selection and services.
 */
async removeProject(slug: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_project", { slug }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the currently selected project slug
 */
async getCurrentProject() : Promise<Result<string | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the current project by slug and connect to its backend
 */
async setCurrentProject(slug: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_current_project", { slug }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if a project is currently selected and database is connected
 */
async hasProjectSelected() : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_project_selected") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List tasks with optional filters
 * 
 * Returns a list of task summaries matching the filter criteria.
 */
async listTasks(filter: TaskFilterOptions | null) : Promise<Result<Task[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tasks", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single task by ID with its relations
 * 
 * Returns the full task details.
 */
async getTask(id: string) : Promise<Result<Task, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the parent task
 * 
 * Sets the parent of the given task. If the task already has a parent, it will be replaced.
 * Validates that both tasks exist.
 */
async setParent(taskId: string, parentId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_parent", { taskId, parentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove the parent task
 * 
 * Removes the parent relationship from the given task, making it a root task.
 */
async removeParent(taskId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_parent", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a dependency relationship
 * 
 * Makes the given task depend on another task (the task is blocked by the dependency).
 * Validates that both tasks exist and that adding the dependency won't create a cycle.
 */
async addDependency(taskId: string, dependsOnId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_dependency", { taskId, dependsOnId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a dependency relationship
 * 
 * Removes a dependency from the given task (the task is no longer blocked by this dependency).
 */
async removeDependency(taskId: string, dependsOnId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_dependency", { taskId, dependsOnId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new task with the given title, optional description, level, and parent task
 * 
 * Returns the ID of the newly created task.
 * Validates that parent task exists if specified.
 */
async createTask(title: string, description: string | null, level: string | null, parentId: string | null) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_task", { title, description, level, parentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a task with multiple fields
 * 
 * Specify only the fields you want to update. Omitted fields remain unchanged.
 */
async updateTask(taskId: string, options: UpdateTaskOptions) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_task", { taskId, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Assign a workflow to a task
 * 
 * Associates the given workflow with the task for workflow state management.
 */
async assignWorkflow(taskId: string, workflowId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("assign_workflow", { taskId, workflowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a task with optional cascade delete for child tasks
 * 
 * When cascade is true, deletes the task and all its descendants.
 * When cascade is false, deletes the task but orphans its children (they lose their parent).
 * 
 * This operation is atomic - either fully succeeds or fully fails.
 */
async deleteTask(taskId: string, cascade: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_task", { taskId, cascade }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a section to a task
 * 
 * Creates a new section with the given type and content.
 * For step and testing_criterion types, content can be optional.
 * The order is automatically assigned based on existing sections of the same type.
 */
async addSection(taskId: string, sectionType: string, content: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_section", { taskId, sectionType, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Edit a section's content by its ordinal (position)
 * 
 * Updates the content of an existing section identified by its type and ordinal.
 */
async editSection(taskId: string, sectionType: string, ordinal: number, newContent: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_section", { taskId, sectionType, ordinal, newContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle the completion status of a step section
 * 
 * Marks a step section as done or not done by toggling its done flag.
 * For step sections only (other types will return an error).
 */
async markSectionDone(taskId: string, ordinal: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_section_done", { taskId, ordinal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a section from a task by its ordinal (position)
 * 
 * Deletes a section identified by its type and ordinal.
 * Remaining sections of the same type are renumbered.
 */
async removeSection(taskId: string, sectionType: string, ordinal: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_section", { taskId, sectionType, ordinal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a code reference to a testing criterion section
 * 
 * Appends a code reference to an existing testing criterion section.
 */
async addCriterionRef(taskId: string, sectionOrdinal: number, filePath: string, lineNumber: number | null, name: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_criterion_ref", { taskId, sectionOrdinal, filePath, lineNumber, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a code reference to a task
 * 
 * Appends a code reference with optional line numbers and description.
 */
async addCodeRef(taskId: string, path: string, lineStart: number | null, lineEnd: number | null, name: string | null, description: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_code_ref", { taskId, path, lineStart, lineEnd, name, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove code references from a task
 * 
 * Deletes one or more code references from the given task.
 * 
 * * `indices` - If provided, only these 0-based indices will be removed. Otherwise all are removed.
 */
async removeCodeRefs(taskId: string, indices: number[] | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_code_refs", { taskId, indices }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replace all code references for a task
 * 
 * Removes all existing code references and adds the provided ones.
 */
async replaceCodeRefs(taskId: string, refs: CodeRef[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_code_refs", { taskId, refs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all workflows
 * 
 * Returns a list of all workflows in the database.
 */
async listWorkflows() : Promise<Result<Workflow[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workflows") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single workflow by ID
 * 
 * Returns the full workflow details including steps.
 */
async getWorkflow(id: string) : Promise<Result<Workflow, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workflow", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a workflow with its associated tasks
 * 
 * Returns the workflow along with all tasks that reference this workflow.
 */
async getWorkflowWithTasks(id: string) : Promise<Result<WorkflowWithTasks, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workflow_with_tasks", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a workflow with its associated tasks including full details and relations
 * 
 * Returns the workflow along with all tasks that reference this workflow,
 * including full task details (sections, refs) and relations (parent, children, dependencies).
 * Uses optimized single-query database access via graph traversal.
 */
async getWorkflowWithTaskDetails(id: string) : Promise<Result<WorkflowWithTaskDetails, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workflow_with_task_details", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all pipeline data in a single command.
 * 
 * Fetches workflows, all tasks (as lightweight summaries), all steps grouped
 * by workflow, and workflow transitions. Replaces the N+1 sequential fetch
 * pattern where each workflow triggers individual task and step queries.
 * 
 * Makes 3-4 service calls total instead of 2N+2.
 */
async getPipelineData() : Promise<Result<PipelineData, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pipeline_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all workflow transitions
 * 
 * Returns all defined transitions between workflows, including workflow names.
 */
async listWorkflowTransitions() : Promise<Result<WorkflowTransition[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workflow_transitions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all step executions for a task
 * 
 * Returns a chronological list of all step executions for the given task.
 * This shows how the task has progressed through workflow steps over time.
 */
async getTaskExecutions(taskId: string) : Promise<Result<StepExecution[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task_executions", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all session logs for a step execution
 * 
 * Returns a chronological list of all session logs for the given execution.
 * This shows the content recorded during the step execution.
 */
async getExecutionLogs(executionId: string) : Promise<Result<SessionLog[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_execution_logs", { executionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all steps for a workflow
 * 
 * Returns all first-class Step entities associated with the given workflow ID.
 */
async listStepsForWorkflow(workflowId: string) : Promise<Result<Step[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_steps_for_workflow", { workflowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single step by ID
 * 
 * Returns the Step entity with the given ID.
 */
async getStep(stepId: string) : Promise<Result<Step | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_step", { stepId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new step for a workflow
 * 
 * Creates a new first-class Step entity with the given properties.
 */
async createStep(workflowId: string, name: string, goal: string | null, agents: string[], skills: string[], order: number, isFinal: boolean, transitionsTo: string[]) : Promise<Result<Step, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_step", { workflowId, name, goal, agents, skills, order, isFinal, transitionsTo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing step
 * 
 * Updates the step with the given ID. Only fields that are Some will be updated.
 */
async updateStep(stepId: string, name: string | null, goal: string | null, agents: string[] | null, skills: string[] | null, order: number | null, isFinal: boolean | null, transitionsTo: string[] | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_step", { stepId, name, goal, agents, skills, order, isFinal, transitionsTo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a step
 * 
 * Deletes the step with the given ID.
 */
async deleteStep(stepId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_step", { stepId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start a workflow execution for a task
 */
async runWorkflow(taskId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_workflow", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new PTY session with the user's default shell
 * 
 * Returns the session ID on success. The PTY will emit PtyOutputEvent for output
 * and PtyExitEvent when the session ends.
 */
async createPtySession(sessionId: string, cols: number, rows: number, workingDir: string | null) : Promise<Result<null, PtyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_pty_session", { sessionId, cols, rows, workingDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write data to a PTY session
 * 
 * The data should be base64-encoded bytes.
 */
async writePty(sessionId: string, data: string) : Promise<Result<null, PtyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_pty", { sessionId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resize a PTY session
 */
async resizePty(sessionId: string, cols: number, rows: number) : Promise<Result<null, PtyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_pty", { sessionId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close a PTY session
 */
async closePtySession(sessionId: string) : Promise<Result<null, PtyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_pty_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
ptyExitEvent: PtyExitEvent,
ptyOutputEvent: PtyOutputEvent,
stepChangedEvent: StepChangedEvent,
stepExecutionChangedEvent: StepExecutionChangedEvent,
taskChangedEvent: TaskChangedEvent,
taskStepChangedEvent: TaskStepChangedEvent,
workflowChangedEvent: WorkflowChangedEvent,
workflowExecutionEvent: WorkflowExecutionEvent
}>({
ptyExitEvent: "pty-exit-event",
ptyOutputEvent: "pty-output-event",
stepChangedEvent: "step-changed-event",
stepExecutionChangedEvent: "step-execution-changed-event",
taskChangedEvent: "task-changed-event",
taskStepChangedEvent: "task-step-changed-event",
workflowChangedEvent: "workflow-changed-event",
workflowExecutionEvent: "workflow-execution-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Agent configuration for workflow steps - mirrors db::AgentConfig
 */
export type AgentConfig = { 
/**
 * Model for the current session
 */
model: string | null; 
/**
 * Fallback model when default model is overloaded
 */
fallback_model: string | null; 
/**
 * System prompt to use for the session
 */
system_prompt: string | null; 
/**
 * Append a system prompt to the default system prompt
 */
append_system_prompt: string | null; 
/**
 * JSON object defining custom agents (serialized as JSON string)
 */
agents: string | null; 
/**
 * List of available tools from the built-in set
 */
tools: string[]; 
/**
 * List of tool names to allow
 */
allowed_tools: string[]; 
/**
 * List of tool names to deny
 */
disallowed_tools: string[]; 
/**
 * Permission mode to use for the session
 */
permission_mode: PermissionMode | null; 
/**
 * Maximum dollar amount to spend on API calls
 */
max_budget_usd: number | null; 
/**
 * Paths to MCP server configuration files or JSON strings
 */
mcp_config: string[]; 
/**
 * Directories to load plugins from
 */
plugin_dirs: string[]; 
/**
 * JSON Schema for structured output validation (serialized as JSON string)
 */
json_schema: string | null }
/**
 * Code reference - file location reference
 */
export type CodeRef = { 
/**
 * Path to the file (relative to repository root)
 */
path: string; 
/**
 * Optional starting line number
 */
line_start: number | null; 
/**
 * Optional ending line number
 */
line_end: number | null; 
/**
 * Optional name/label for this reference
 */
name: string | null; 
/**
 * Optional description
 */
description: string | null }
/**
 * Error response type for commands - simple string wrapper with specta support
 */
export type CommandError = { message: string }
/**
 * Execution status - mirrors db::ExecutionStatus
 */
export type ExecutionStatus = "in_progress" | "completed" | "failed"
/**
 * Permission mode for agent sessions - mirrors db::PermissionMode
 */
export type PermissionMode = "accept_edits" | "bypass_permissions" | "default" | "delegate" | "dont_ask" | "plan"
/**
 * Aggregated data for the pipeline view, loaded in a single command.
 * Replaces N+1 sequential HTTP calls with 3 batch calls.
 */
export type PipelineData = { workflows: Workflow[]; workflow_steps: Partial<{ [key in string]: Step[] }>; tasks: Task[]; transitions: WorkflowTransition[] }
/**
 * PTY operation errors
 */
export type PtyError = { SpawnFailed: string } | { SessionNotFound: string } | { WriteFailed: string } | { ResizeFailed: string }
/**
 * Event emitted when PTY session ends
 */
export type PtyExitEvent = { session_id: string; 
/**
 * Exit code if process exited normally
 */
exit_code: number | null; 
/**
 * Error message if process failed
 */
error: string | null }
/**
 * Event emitted when PTY produces output
 */
export type PtyOutputEvent = { session_id: string; 
/**
 * Raw output bytes encoded as base64 to preserve binary data
 */
data: string }
/**
 * A saved project in the project list
 */
export type SavedProject = { 
/**
 * Project slug (from config.toml key)
 */
slug: string; 
/**
 * Sacrum project ID (UUID)
 */
project_id: string; 
/**
 * Optional per-project URL override
 */
url?: string | null }
/**
 * Section content within a task
 */
export type Section = { 
/**
 * The type of this section
 */
type: SectionType; 
/**
 * The content of this section
 */
content: string; 
/**
 * Optional ordering for sections of the same type
 */
order: number | null; 
/**
 * Whether this section (typically a step) is done
 */
done: boolean | null; 
/**
 * When this section was marked as done (ISO 8601 string)
 */
done_at: string | null; 
/**
 * Code references attached to this section
 */
refs?: CodeRef[] }
/**
 * Section type - mirrors db::SectionType
 */
export type SectionType = "goal" | "context" | "current_behavior" | "desired_behavior" | "step" | "testing_criterion" | "anti_pattern" | "failure_test" | "constraint"
/**
 * Session log entry - mirrors db::SessionLog
 */
export type SessionLog = { 
/**
 * Log ID (string form)
 */
id: string | null; 
/**
 * Step execution ID this log belongs to
 */
step_execution_id: string; 
/**
 * The log content
 */
content: string; 
/**
 * When this log was created (ISO 8601 string)
 */
created_at: string }
/**
 * Workflow step entity - mirrors db::Step
 */
export type Step = { 
/**
 * Step ID (string form)
 */
id: string | null; 
/**
 * Display name for this step
 */
name: string; 
/**
 * Reference to the workflow this step belongs to
 */
workflow_id: string; 
/**
 * What this step should accomplish
 */
goal: string | null; 
/**
 * Paths to .claude/agents/ files for this step
 */
agents?: string[]; 
/**
 * Skill names available for this step
 */
skills?: string[]; 
/**
 * Agent configuration for this step
 */
agent_config: AgentConfig; 
/**
 * Whether this is a final step (no outgoing transitions)
 */
is_final: boolean; 
/**
 * List of step IDs this step can transition to
 */
transitions_to: string[]; 
/**
 * Ordering index for sequential fallback (0-based)
 */
order: number; 
/**
 * Creation timestamp (ISO 8601 string)
 */
created_at: string | null; 
/**
 * Last update timestamp (ISO 8601 string)
 */
updated_at: string | null }
/**
 * The type of change that occurred on a step.
 */
export type StepChangeType = "Created" | "Updated" | "Deleted"
/**
 * Event payload for step changes.
 * Emitted when a step is created, updated, or deleted.
 */
export type StepChangedEvent = { step_id: string; workflow_id: string; change_type: StepChangeType }
/**
 * Step execution record - mirrors db::StepExecution
 */
export type StepExecution = { 
/**
 * Execution ID (string form)
 */
id: string | null; 
/**
 * Task ID this execution belongs to
 */
task_id: string; 
/**
 * Workflow ID being executed
 */
workflow_id: string; 
/**
 * Name of the step being executed
 */
step_name: string; 
/**
 * When this step execution started (ISO 8601 string)
 */
started_at: string; 
/**
 * When this step execution completed (ISO 8601 string)
 */
completed_at: string | null; 
/**
 * Current status of this step execution
 */
status: ExecutionStatus }
/**
 * The type of change that occurred on a step execution.
 */
export type StepExecutionChangeType = "Created" | "StatusChanged"
/**
 * Event payload for step execution changes.
 * Emitted when a step execution is created or its status changes.
 */
export type StepExecutionChangedEvent = { execution_id: string; task_id: string; workflow_id: string; step_name: string; status: StepExecutionStatus; change_type: StepExecutionChangeType }
/**
 * Status of a step execution (mirrors db::ExecutionStatus for frontend)
 */
export type StepExecutionStatus = "Pending" | "Running" | "Completed" | "Failed"
/**
 * Full task details - mirrors core::Task with string IDs and dates
 */
export type Task = { 
/**
 * Task ID (string form)
 */
id: string; 
/**
 * Task title
 */
title: string; 
/**
 * Optional description
 */
description: string | null; 
/**
 * Hierarchy level
 */
level: TaskLevel; 
/**
 * Optional priority
 */
priority: TaskPriority | null; 
/**
 * Tags for categorization
 */
tags: string[]; 
/**
 * Workflow ID (string form)
 */
workflow_id: string | null; 
/**
 * Current step ID (string form) - used for positioning
 */
current_step_id: string | null; 
/**
 * Workflow name (if task is assigned to a workflow)
 */
workflow_name: string | null; 
/**
 * Current step name (if task has a current step in workflow)
 */
step_name: string | null; 
/**
 * Whether this task needs human review
 */
needs_human_review: boolean | null; 
/**
 * Review comment
 */
review_comment: string | null; 
/**
 * Feedback to address when a validation gate fails
 */
revision_feedback: string | null; 
/**
 * Reason why the task was rejected
 */
rejection_reason: string | null; 
/**
 * Parent task ID (if any)
 */
parent_id: string | null; 
/**
 * IDs of tasks this task depends on
 */
dependency_ids?: string[]; 
/**
 * Embedded sections
 */
sections: Section[]; 
/**
 * Embedded code references
 */
code_refs: CodeRef[]; 
/**
 * Creation timestamp (ISO 8601 string)
 */
created_at: string | null; 
/**
 * Last update timestamp (ISO 8601 string)
 */
updated_at: string | null; 
/**
 * When this task was started (ISO 8601 string)
 */
started_at: string | null; 
/**
 * When this task was completed (ISO 8601 string)
 */
completed_at: string | null }
/**
 * The type of change that occurred on a task.
 */
export type TaskChangeType = "Created" | "Updated" | "Deleted" | "StatusChanged"
/**
 * Event payload for task changes.
 * Emitted when a task is created, updated, deleted, or its status changes.
 */
export type TaskChangedEvent = { task_id: string; change_type: TaskChangeType }
/**
 * Filter options for listing tasks
 */
export type TaskFilterOptions = { 
/**
 * Filter by step names (OR semantics) - workflow step names
 */
step_names: string[] | null; 
/**
 * Filter by levels (OR semantics)
 */
levels: TaskLevel[] | null; 
/**
 * Filter by tags (OR semantics)
 */
tags: string[] | null; 
/**
 * Show only root items (no parent)
 */
root_only: boolean | null; 
/**
 * Show only children of a specific task
 */
children_of: string | null; 
/**
 * Include done items (excluded by default)
 */
include_done: boolean | null; 
/**
 * Search text in title and description
 */
search: string | null; 
/**
 * Filter by workflow_id (tasks assigned to a specific workflow)
 */
workflow_id: string | null }
/**
 * Task hierarchy level - mirrors db::Level
 */
export type TaskLevel = "epic" | "ticket" | "task"
/**
 * Task priority - mirrors db::Priority
 */
export type TaskPriority = "low" | "medium" | "high" | "critical"
/**
 * Event payload for task current step changes.
 * Emitted when a task's current_step_id is updated during workflow execution.
 * Includes the new step info so frontend can update directly without refetching.
 */
export type TaskStepChangedEvent = { task_id: string; step_id: string; step_name: string }
/**
 * Options for updating a task - allows updating multiple fields at once
 */
export type UpdateTaskOptions = { 
/**
 * New title (if provided)
 */
title: string | null; 
/**
 * New description (if provided, null clears it)
 */
description: string | null; 
/**
 * New priority (if provided, null clears it)
 */
priority: string | null; 
/**
 * Tags to add
 */
add_tags?: string[]; 
/**
 * Tags to remove
 */
remove_tags?: string[]; 
/**
 * New task level (epic, ticket, task)
 */
level: string | null; 
/**
 * Human review flag
 */
needs_human_review: boolean | null; 
/**
 * Revision feedback text
 */
revision_feedback: string | null }
/**
 * Workflow - mirrors db::Workflow
 */
export type Workflow = { 
/**
 * Workflow ID (string form)
 */
id: string | null; 
/**
 * Workflow name
 */
name: string; 
/**
 * Optional description of the workflow
 */
description: string | null; 
/**
 * Reference to the initial step in the workflow
 */
initial_step: string | null; 
/**
 * Additional metadata as key-value pairs
 */
metadata: Partial<{ [key in string]: string }>; 
/**
 * Creation timestamp (ISO 8601 string)
 */
created_at: string | null; 
/**
 * Last update timestamp (ISO 8601 string)
 */
updated_at: string | null }
/**
 * The type of change that occurred on a workflow.
 */
export type WorkflowChangeType = "Created" | "Updated" | "Deleted" | 
/**
 * A task was assigned to this workflow
 */
"TaskAssigned" | 
/**
 * A task was unassigned from a workflow
 */
"TaskUnassigned"
/**
 * Event payload for workflow changes.
 * Emitted when a workflow is created, updated, or deleted.
 */
export type WorkflowChangedEvent = { workflow_id: string; change_type: WorkflowChangeType }
/**
 * Event payload for workflow execution progress.
 * Emitted during workflow step execution to track progress.
 */
export type WorkflowExecutionEvent = { task_id: string; workflow_id: string; event_type: WorkflowExecutionEventType }
/**
 * The type of execution event that occurred.
 */
export type WorkflowExecutionEventType = 
/**
 * Workflow execution started
 */
"Started" | 
/**
 * Orchestrator phase started
 */
{ OrchestratorStarted: { execution_id: string; step_name: string } } | 
/**
 * Orchestrator phase completed, prompt ready
 */
{ OrchestratorCompleted: { execution_id: string } } | 
/**
 * Orchestrator phase failed
 */
{ OrchestratorFailed: { execution_id: string; error: string } } | 
/**
 * A step execution started (execution phase)
 */
{ StepStarted: { execution_id: string; step_name: string } } | 
/**
 * Step produced output
 */
{ StepProgress: { execution_id: string; output_lines: string[] } } | 
/**
 * A step completed successfully
 */
{ StepCompleted: { execution_id: string } } | 
/**
 * A step failed
 */
{ StepFailed: { execution_id: string; error: string } } | 
/**
 * Entire workflow completed successfully
 */
"Completed" | 
/**
 * Workflow failed
 */
{ Failed: { error: string } }
/**
 * Workflow transition - defines allowed transitions between workflows
 */
export type WorkflowTransition = { 
/**
 * Transition ID (string form)
 */
id: string | null; 
/**
 * Source workflow ID
 */
from_workflow_id: string; 
/**
 * Source workflow name
 */
from_workflow_name: string; 
/**
 * Target workflow ID
 */
to_workflow_id: string; 
/**
 * Target workflow name
 */
to_workflow_name: string; 
/**
 * Human-readable label for this transition
 */
label: string; 
/**
 * Optional target step ID in the destination workflow
 */
target_step_id: string | null }
/**
 * Workflow with its associated tasks including full details
 */
export type WorkflowWithTaskDetails = { 
/**
 * The workflow itself
 */
workflow: Workflow; 
/**
 * Tasks associated with this workflow
 */
tasks: Task[] }
/**
 * Workflow with its associated tasks
 */
export type WorkflowWithTasks = { 
/**
 * The workflow itself
 */
workflow: Workflow; 
/**
 * Tasks associated with this workflow
 */
tasks: Task[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
