/* eslint-disable */
// @ts-nocheck
// This file was auto-generated by tauri-specta. Do not edit.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Example command that will be exported with type definitions.
 * This serves as a template for future Tauri commands.
 */
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
/**
 * Get the list of saved projects
 */
async getProjects() : Promise<Result<SavedProject[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a project to the saved list
 * 
 * Takes a directory path, derives a slug from the folder name,
 * creates the project in Sacrum API if needed, and registers in global config.
 */
async addProject(path: string) : Promise<Result<SavedProject, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a project from the saved list
 * 
 * Removes the project from config.toml by slug. If the removed project
 * is the currently selected project, clears the selection and services.
 */
async removeProject(slug: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_project", { slug }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the currently selected project slug
 */
async getCurrentProject() : Promise<Result<string | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the currently selected project's git root path
 */
async getCurrentProjectPath() : Promise<Result<string | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_project_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the current project by slug and connect to its backend
 */
async setCurrentProject(slug: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_current_project", { slug }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if a project is currently selected and database is connected
 */
async hasProjectSelected() : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_project_selected") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List tasks with optional filters
 * 
 * Returns a list of task summaries matching the filter criteria.
 */
async listTasks(filter: TaskFilterOptions | null) : Promise<Result<Task[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tasks", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single task by ID with its relations
 * 
 * Returns the full task details.
 */
async getTask(id: string) : Promise<Result<Task, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the parent task
 * 
 * Sets the parent of the given task. If the task already has a parent, it will be replaced.
 * Validates that both tasks exist.
 */
async setParent(taskId: string, parentId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_parent", { taskId, parentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove the parent task
 * 
 * Removes the parent relationship from the given task, making it a root task.
 */
async removeParent(taskId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_parent", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a dependency relationship
 * 
 * Makes the given task depend on another task (the task is blocked by the dependency).
 * Validates that both tasks exist and that adding the dependency won't create a cycle.
 */
async addDependency(taskId: string, dependsOnId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_dependency", { taskId, dependsOnId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a dependency relationship
 * 
 * Removes a dependency from the given task (the task is no longer blocked by this dependency).
 */
async removeDependency(taskId: string, dependsOnId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_dependency", { taskId, dependsOnId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new task with the given title, optional description, level, and parent task
 * 
 * Returns the ID of the newly created task.
 * Validates that parent task exists if specified.
 */
async createTask(title: string, description: string | null, level: string | null, parentId: string | null) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_task", { title, description, level, parentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a task with multiple fields
 * 
 * Specify only the fields you want to update. Omitted fields remain unchanged.
 */
async updateTask(taskId: string, options: UpdateTaskOptions) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_task", { taskId, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Assign a workflow to a task
 * 
 * Associates the given workflow with the task for workflow state management.
 */
async assignWorkflow(taskId: string, workflowId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("assign_workflow", { taskId, workflowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a task with optional cascade delete for child tasks
 * 
 * When cascade is true, deletes the task and all its descendants.
 * When cascade is false, deletes the task but orphans its children (they lose their parent).
 * 
 * This operation is atomic - either fully succeeds or fully fails.
 */
async deleteTask(taskId: string, cascade: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_task", { taskId, cascade }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a section to a task
 * 
 * Creates a new section with the given type and content.
 * For step and testing_criterion types, content can be optional.
 * The order is automatically assigned based on existing sections of the same type.
 */
async addSection(taskId: string, sectionType: string, content: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_section", { taskId, sectionType, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Edit a section's content by its ordinal (position)
 * 
 * Updates the content of an existing section identified by its type and ordinal.
 */
async editSection(taskId: string, sectionType: string, ordinal: number, newContent: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_section", { taskId, sectionType, ordinal, newContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle the completion status of a checklist item
 * 
 * Marks a checklist item as done or not done by toggling its done flag.
 * For checklist item sections only (other types will return an error).
 */
async toggleChecklistItemDone(taskId: string, ordinal: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_checklist_item_done", { taskId, ordinal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a section from a task by its ordinal (position)
 * 
 * Deletes a section identified by its type and ordinal.
 * Remaining sections of the same type are renumbered.
 */
async removeSection(taskId: string, sectionType: string, ordinal: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_section", { taskId, sectionType, ordinal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a code reference to a testing criterion section
 * 
 * Appends a code reference to an existing testing criterion section.
 */
async addCriterionRef(taskId: string, sectionOrdinal: number, filePath: string, lineNumber: number | null, name: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_criterion_ref", { taskId, sectionOrdinal, filePath, lineNumber, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a code reference to a task
 * 
 * Appends a code reference with optional line numbers and description.
 */
async addCodeRef(taskId: string, path: string, lineStart: number | null, lineEnd: number | null, name: string | null, description: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_code_ref", { taskId, path, lineStart, lineEnd, name, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove code references from a task
 * 
 * Deletes one or more code references from the given task.
 * 
 * * `indices` - If provided, only these 0-based indices will be removed. Otherwise all are removed.
 */
async removeCodeRefs(taskId: string, indices: number[] | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_code_refs", { taskId, indices }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replace all code references for a task
 * 
 * Removes all existing code references and adds the provided ones.
 */
async replaceCodeRefs(taskId: string, refs: CodeRef[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_code_refs", { taskId, refs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all workflows
 * 
 * Returns a list of all workflows in the database.
 */
async listWorkflows() : Promise<Result<Workflow[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workflows") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single workflow by ID
 * 
 * Returns the full workflow details including steps.
 */
async getWorkflow(id: string) : Promise<Result<Workflow, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workflow", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a workflow with its associated tasks
 * 
 * Returns the workflow along with all tasks that reference this workflow.
 */
async getWorkflowWithTasks(id: string) : Promise<Result<WorkflowWithTasks, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workflow_with_tasks", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a workflow with its associated tasks including full details and relations
 * 
 * Returns the workflow along with all tasks that reference this workflow,
 * including full task details (sections, refs) and relations (parent, children, dependencies).
 * Uses optimized single-query database access via graph traversal.
 */
async getWorkflowWithTaskDetails(id: string) : Promise<Result<WorkflowWithTaskDetails, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workflow_with_task_details", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the full pipeline summary in a single GraphQL round-trip.
 * 
 * Returns one entry per workflow with preloaded steps (each carrying
 * `task_counts` and `running_count` aggregates plus their outbound
 * transitions) and inter-workflow transitions. The Sacrum resolver runs at
 * most 4 SQL queries regardless of project size.
 * 
 * The frontend keeps these aggregates fresh from WebSocket events; it does
 * NOT refetch on every change, and it does NOT issue a per-task execution
 * query on mount.
 */
async getPipelineSummary() : Promise<Result<PipelineSummary, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pipeline_summary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all workflow transitions
 * 
 * Returns all defined transitions between workflows, including workflow names.
 */
async listWorkflowTransitions() : Promise<Result<WorkflowTransition[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workflow_transitions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all step executions for a task
 * 
 * Returns a chronological list of all step executions for the given task.
 * This shows how the task has progressed through workflow steps over time.
 */
async getTaskExecutions(taskId: string) : Promise<Result<StepExecution[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task_executions", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch a single step execution by ID with full detail.
 * 
 * Returns the full StepExecution struct (including prompt, output, context,
 * transition_result, model, tokens, cost, duration_ms, handoff, session_id)
 * or `None` when no execution matches the given ID.
 */
async getExecution(executionId: string) : Promise<Result<StepExecution | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_execution", { executionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all session logs for a step execution
 * 
 * Returns a chronological list of all session logs for the given execution.
 * This shows the content recorded during the step execution.
 */
async getExecutionLogs(executionId: string) : Promise<Result<SessionLog[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_execution_logs", { executionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all steps for a workflow
 * 
 * Returns all first-class Step entities associated with the given workflow ID.
 */
async listStepsForWorkflow(workflowId: string) : Promise<Result<Step[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_steps_for_workflow", { workflowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single step by ID
 * 
 * Returns the Step entity with the given ID.
 */
async getStep(stepId: string) : Promise<Result<Step | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_step", { stepId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new step for a workflow
 * 
 * Creates a new first-class Step entity with the given properties.
 */
async createStep(options: CreateStepOptions) : Promise<Result<Step, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_step", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing step
 * 
 * Updates the step with the given ID. Only fields that are Some will be updated.
 */
async updateStep(options: UpdateStepOptions) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_step", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a step
 * 
 * Deletes the step with the given ID.
 */
async deleteStep(stepId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_step", { stepId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run a single workflow step for a task via Sacrum
 * 
 * Sacrum creates a StepExecution record and broadcasts a run_step event
 * to connected daemon clients, which pick up and execute the step.
 */
async runStep(taskId: string, stepId: string) : Promise<Result<StepExecution, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_step", { taskId, stepId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Orchestrate a task through its entire workflow via Sacrum's TaskOrchestrator FSM
 */
async orchestrateTask(taskId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("orchestrate_task", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new Claude session with JSONL streaming
 * 
 * Spawns the Claude CLI with streaming JSON input/output mode.
 * If `resume_session_id` is provided, continues an existing conversation.
 * Returns immediately; the session emits events for all output.
 */
async createClaudeSession(sessionId: string, workingDir: string | null, initialPrompt: string | null, resumeSessionId: string | null) : Promise<Result<null, ClaudeSessionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_claude_session", { sessionId, workingDir, initialPrompt, resumeSessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a message to a Claude session
 * 
 * Sends a user message to an active Claude session via stdin.
 */
async sendClaudeMessage(sessionId: string, content: string) : Promise<Result<null, ClaudeSessionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_claude_message", { sessionId, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close a Claude session
 * 
 * Terminates the Claude CLI process for the given session.
 */
async closeClaudeSession(sessionId: string) : Promise<Result<null, ClaudeSessionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_claude_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current WebSocket connection status
 */
async getWebsocketStatus() : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_websocket_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
claudePermissionRequestEvent: ClaudePermissionRequestEvent,
claudeSessionEndEvent: ClaudeSessionEndEvent,
claudeSessionErrorEvent: ClaudeSessionErrorEvent,
claudeSessionInitEvent: ClaudeSessionInitEvent,
claudeTextEvent: ClaudeTextEvent,
claudeToolCallEvent: ClaudeToolCallEvent,
claudeToolResultEvent: ClaudeToolResultEvent,
sectionChangedEvent: SectionChangedEvent,
sessionLogCreatedEvent: SessionLogCreatedEvent,
stepChangedEvent: StepChangedEvent,
stepExecutionChangedEvent: StepExecutionChangedEvent,
stepTransitionChangedEvent: StepTransitionChangedEvent,
taskChangedEvent: TaskChangedEvent,
taskStepChangedEvent: TaskStepChangedEvent,
workflowChangedEvent: WorkflowChangedEvent
}>({
claudePermissionRequestEvent: "claude-permission-request-event",
claudeSessionEndEvent: "claude-session-end-event",
claudeSessionErrorEvent: "claude-session-error-event",
claudeSessionInitEvent: "claude-session-init-event",
claudeTextEvent: "claude-text-event",
claudeToolCallEvent: "claude-tool-call-event",
claudeToolResultEvent: "claude-tool-result-event",
sectionChangedEvent: "section-changed-event",
sessionLogCreatedEvent: "session-log-created-event",
stepChangedEvent: "step-changed-event",
stepExecutionChangedEvent: "step-execution-changed-event",
stepTransitionChangedEvent: "step-transition-changed-event",
taskChangedEvent: "task-changed-event",
taskStepChangedEvent: "task-step-changed-event",
workflowChangedEvent: "workflow-changed-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Agent configuration for workflow steps - mirrors db::AgentConfig
 */
export type AgentConfig = { 
/**
 * Model for the current session
 */
model: string | null; 
/**
 * Fallback model when default model is overloaded
 */
fallback_model: string | null; 
/**
 * System prompt to use for the session
 */
system_prompt: string | null; 
/**
 * Append a system prompt to the default system prompt
 */
append_system_prompt: string | null; 
/**
 * JSON object defining custom agents (serialized as JSON string)
 */
agents: string | null; 
/**
 * List of available tools from the built-in set
 */
tools?: string[]; 
/**
 * List of tool names to allow
 */
allowed_tools?: string[]; 
/**
 * List of tool names to deny
 */
disallowed_tools?: string[]; 
/**
 * Permission mode to use for the session
 */
permission_mode: PermissionMode | null; 
/**
 * Maximum dollar amount to spend on API calls
 */
max_budget_usd: number | null; 
/**
 * Paths to MCP server configuration files or JSON strings
 */
mcp_config?: string[]; 
/**
 * Directories to load plugins from
 */
plugin_dirs?: string[]; 
/**
 * JSON Schema for structured output validation (serialized as JSON string)
 */
json_schema: string | null }
/**
 * Event emitted when Claude requests permission
 */
export type ClaudePermissionRequestEvent = { session_id: string; tool_name: string; permission_message: string }
/**
 * Event emitted when Claude session ends
 */
export type ClaudeSessionEndEvent = { session_id: string; duration_ms: number; cost_usd: number; num_turns: number; result: string; is_error: boolean; 
/**
 * Total tokens used in context (input + cache)
 */
context_tokens: number; 
/**
 * Maximum context window size
 */
context_window: number }
/**
 * Claude session errors
 */
export type ClaudeSessionError = { SessionExists: string } | { SessionNotFound: string } | { SendFailed: string } | { SpawnFailed: string }
/**
 * Event emitted when Claude session encounters an error
 */
export type ClaudeSessionErrorEvent = { session_id: string; error: string }
/**
 * Event emitted when Claude session initializes
 */
export type ClaudeSessionInitEvent = { session_id: string; 
/**
 * Claude's conversation ID - use this with --resume for multi-turn
 */
claude_conversation_id: string | null; model: string; tools: string[] }
/**
 * Event emitted when Claude produces text output
 */
export type ClaudeTextEvent = { session_id: string; text: string; 
/**
 * Whether this is a partial (streaming) message
 */
is_partial: boolean }
/**
 * Event emitted when Claude calls a tool
 */
export type ClaudeToolCallEvent = { session_id: string; tool_id: string; tool_name: string; input: string }
/**
 * Event emitted when a tool returns a result
 */
export type ClaudeToolResultEvent = { session_id: string; tool_id: string; result: string; is_error: boolean }
/**
 * Code reference - file location reference
 */
export type CodeRef = { 
/**
 * Path to the file (relative to repository root)
 */
path: string; 
/**
 * Optional starting line number
 */
line_start: number | null; 
/**
 * Optional ending line number
 */
line_end: number | null; 
/**
 * Optional name/label for this reference
 */
name: string | null; 
/**
 * Optional description
 */
description: string | null }
/**
 * Error response type for commands - simple string wrapper with specta support
 */
export type CommandError = { message: string }
/**
 * Options for creating a workflow step.
 */
export type CreateStepOptions = { workflow_id: string; name: string; goal: string | null; agents: string[]; skills: string[]; order: number; is_final: boolean; transitions_to: string[]; step_type?: StepType; output_schema: JsonValue | null }
/**
 * Execution status - mirrors db::ExecutionStatus
 */
export type ExecutionStatus = "in_progress" | "completed" | "failed"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Permission mode for agent sessions - mirrors db::PermissionMode
 */
export type PermissionMode = "accept_edits" | "bypass_permissions" | "default" | "delegate" | "dont_ask" | "plan"
/**
 * Workflow step entry in the pipeline summary payload, including the
 * resolver-computed `task_counts` and `running_count` aggregates and the
 * preloaded list of intra-workflow `transitions_to` step IDs.
 */
export type PipelineStep = { id: string; name: string; workflow_id: string; goal: string | null; step_order: number; step_type: string | null; is_final: boolean; 
/**
 * IDs of the steps that this step transitions into within the same workflow.
 */
transitions_to: string[]; 
/**
 * Per-level task counts for tasks currently parked at this step.
 */
task_counts: PipelineTaskCounts; 
/**
 * Number of step executions in the `started` (running) state for this step.
 */
running_count: number }
/**
 * Full pipeline summary payload returned by `get_pipeline_summary`.
 * 
 * One `PipelineWorkflow` per workflow in the project. There is intentionally
 * no top-level flat task index — the GUI builds one incrementally from
 * `taskChangedEvent` to drive count deltas.
 */
export type PipelineSummary = { workflows: PipelineWorkflow[] }
/**
 * Per-step task counts grouped by hierarchy level — direct mirror of the
 * Sacrum `pipeline_summary.workflow_steps[].task_counts` field.
 */
export type PipelineTaskCounts = { epic: number; ticket: number; task: number }
/**
 * Single workflow entry in the pipeline summary payload, with its preloaded
 * steps (carrying aggregates) and outbound inter-workflow transitions.
 */
export type PipelineWorkflow = { id: string; name: string; description: string | null; initial_step_id: string | null; kanban_column: string | null; is_default: boolean; display_order: number; workflow_steps: PipelineStep[]; transitions: PipelineWorkflowTransition[] }
/**
 * Inter-workflow transition entry returned by `pipeline_summary`.
 */
export type PipelineWorkflowTransition = { id: string; from_workflow_id: string; to_workflow_id: string; target_step_id: string | null; label: string }
/**
 * A saved project in the project list
 */
export type SavedProject = { 
/**
 * Project slug (from config.toml key)
 */
slug: string; 
/**
 * Sacrum project ID (UUID)
 */
project_id: string; 
/**
 * Git root path for the project
 */
path: string }
/**
 * Section content within a task
 */
export type Section = { 
/**
 * The type of this section
 */
type: SectionType; 
/**
 * The content of this section
 */
content: string; 
/**
 * Optional ordering for sections of the same type
 */
order: number | null; 
/**
 * Whether this section (typically a step) is done
 */
done: boolean | null; 
/**
 * When this section was marked as done (ISO 8601 string)
 */
done_at: string | null; 
/**
 * Code references attached to this section
 */
refs?: CodeRef[] }
/**
 * The type of change that occurred on a section.
 */
export type SectionChangeType = "Created" | "Updated" | "Deleted"
/**
 * Event payload for section changes.
 * Emitted when a section is created, updated, or deleted.
 * For create/update events, `section` carries the full deserialized entity.
 */
export type SectionChangedEvent = { section_id: string; task_id: string; change_type: SectionChangeType; section: Section | null }
/**
 * Section type - mirrors db::SectionType
 */
export type SectionType = "goal" | "context" | "current_behavior" | "desired_behavior" | "checklist_item" | "testing_criterion" | "anti_pattern" | "failure_test" | "constraint"
/**
 * Session log entry - mirrors db::SessionLog
 */
export type SessionLog = { 
/**
 * Log ID (string form)
 */
id: string | null; 
/**
 * Step execution ID this log belongs to
 */
step_execution_id?: string; 
/**
 * The log content
 */
content?: string; 
/**
 * When this log was created (ISO 8601 string)
 */
created_at?: string }
/**
 * Event payload for session log creation.
 * Emitted when a new session log is created during step execution.
 * `session_log` carries the full deserialized entity when available.
 */
export type SessionLogCreatedEvent = { log_id: string; step_execution_id: string; session_log: SessionLog | null }
/**
 * Workflow step entity - mirrors db::Step
 */
export type Step = { 
/**
 * Step ID (string form)
 */
id: string | null; 
/**
 * Display name for this step
 */
name: string; 
/**
 * Reference to the workflow this step belongs to
 */
workflow_id: string; 
/**
 * What this step should accomplish
 */
goal: string | null; 
/**
 * Prompt sent to the agent when executing this step
 */
prompt: string | null; 
/**
 * Paths to .claude/agents/ files for this step
 */
agents?: string[]; 
/**
 * Skill names available for this step
 */
skills?: string[]; 
/**
 * Agent configuration for this step
 */
agent_config?: AgentConfig; 
/**
 * The type of this step (execute, evaluate, route)
 */
step_type?: StepType; 
/**
 * JSON Schema describing the expected output of this step
 */
output_schema?: JsonValue | null; 
/**
 * Whether this is a final step (no outgoing transitions)
 */
is_final?: boolean; 
/**
 * List of step IDs this step can transition to
 */
transitions_to?: string[]; 
/**
 * Ordering index for sequential fallback (0-based)
 */
order?: number; 
/**
 * Creation timestamp (ISO 8601 string)
 */
created_at: string | null; 
/**
 * Last update timestamp (ISO 8601 string)
 */
updated_at: string | null }
/**
 * The type of change that occurred on a step.
 */
export type StepChangeType = "Created" | "Updated" | "Deleted"
/**
 * Event payload for step changes.
 * Emitted when a step is created, updated, or deleted.
 * For create/update events, `step` carries the full deserialized entity.
 */
export type StepChangedEvent = { step_id: string; workflow_id: string; change_type: StepChangeType; step: Step | null }
/**
 * Step execution record - mirrors db::StepExecution.
 * 
 * Carries the full sacrum field set so the traces UI can render prompt,
 * output, context, transition_result, model/provider, token usage, cost,
 * duration, handoff, and session_id. All extended fields are `Option`-typed
 * because historical executions and minimal payloads may not populate them.
 */
export type StepExecution = { 
/**
 * Execution ID (string form)
 */
id: string | null; 
/**
 * Task ID this execution belongs to
 */
task_id?: string; 
/**
 * Workflow ID being executed
 */
workflow_id?: string; 
/**
 * Name of the step being executed
 */
step_name?: string; 
/**
 * When this step execution started (ISO 8601 string)
 */
started_at?: string; 
/**
 * When this step execution completed (ISO 8601 string)
 */
completed_at: string | null; 
/**
 * Current status of this step execution
 */
status?: ExecutionStatus; 
/**
 * Prompt text/JSON that drove the execution
 */
prompt?: string | null; 
/**
 * Final output of the execution
 */
output?: string | null; 
/**
 * Execution context (arbitrary JSON serialized as string)
 */
context?: string | null; 
/**
 * Transition decision payload (route/evaluate steps)
 */
transition_result?: string | null; 
/**
 * Model identifier (e.g. "claude-opus-4")
 */
model?: string | null; 
/**
 * Model provider (e.g. "anthropic")
 */
model_provider?: string | null; 
/**
 * Input tokens consumed
 */
input_tokens?: number | null; 
/**
 * Output tokens emitted
 */
output_tokens?: number | null; 
/**
 * Cost in USD
 */
cost?: number | null; 
/**
 * Wall-clock duration in milliseconds
 */
duration_ms?: number | null; 
/**
 * Handoff payload from a route step (JSON encoded)
 */
handoff?: string | null; 
/**
 * Provider session identifier (e.g. Claude session ID)
 */
session_id?: string | null }
/**
 * The type of change that occurred on a step execution.
 */
export type StepExecutionChangeType = "Created" | "StatusChanged"
/**
 * Event payload for step execution changes.
 * Emitted when a step execution is created or its status changes.
 * For create/update events, `execution` carries the full deserialized entity.
 */
export type StepExecutionChangedEvent = { execution_id: string; task_id: string; workflow_id: string; step_name: string; status: StepExecutionStatus; change_type: StepExecutionChangeType; execution: StepExecution | null }
/**
 * Status of a step execution (mirrors db::ExecutionStatus for frontend)
 */
export type StepExecutionStatus = "Pending" | "Running" | "Completed" | "Failed"
/**
 * The type of change that occurred on a step transition.
 */
export type StepTransitionChangeType = "Created" | "Deleted"
/**
 * Event payload for step transition changes.
 * Emitted when a step transition is created or deleted.
 */
export type StepTransitionChangedEvent = { transition_id: string; change_type: StepTransitionChangeType }
/**
 * Step type - mirrors core::StepType
 */
export type StepType = "execute" | "evaluate" | "route" | "wait_children"
/**
 * Full task details - mirrors core::Task with string IDs and dates
 */
export type Task = { 
/**
 * Task ID (string form)
 */
id: string; 
/**
 * Task title
 */
title: string; 
/**
 * Optional description
 */
description: string | null; 
/**
 * Hierarchy level (null when created without explicit level)
 */
level: TaskLevel | null; 
/**
 * Optional priority
 */
priority: TaskPriority | null; 
/**
 * Tags for categorization
 */
tags?: string[]; 
/**
 * Workflow ID (string form)
 */
workflow_id: string | null; 
/**
 * Current step ID (string form) - used for positioning
 */
current_step_id: string | null; 
/**
 * Workflow name (if task is assigned to a workflow)
 */
workflow_name: string | null; 
/**
 * Current step name (if task has a current step in workflow)
 */
step_name: string | null; 
/**
 * Whether this task needs human review
 */
needs_human_review: boolean | null; 
/**
 * Whether this task is archived
 */
archived?: boolean; 
/**
 * Optional worktree path
 */
worktree: string | null; 
/**
 * Review comment
 */
review_comment: string | null; 
/**
 * Feedback to address when a validation gate fails
 */
revision_feedback: string | null; 
/**
 * Reason why the task was rejected
 */
rejection_reason: string | null; 
/**
 * Parent task ID (if any)
 */
parent_id: string | null; 
/**
 * IDs of tasks this task depends on
 */
dependency_ids?: string[]; 
/**
 * Embedded sections
 */
sections?: Section[]; 
/**
 * Embedded code references
 */
code_refs?: CodeRef[]; 
/**
 * Creation timestamp (ISO 8601 string)
 */
created_at: string | null; 
/**
 * Last update timestamp (ISO 8601 string)
 */
updated_at: string | null; 
/**
 * When this task was started (ISO 8601 string)
 */
started_at: string | null; 
/**
 * When this task was completed (ISO 8601 string)
 */
completed_at: string | null }
/**
 * The type of change that occurred on a task.
 */
export type TaskChangeType = "Created" | "Updated" | "Deleted" | "StatusChanged"
/**
 * Event payload for task changes.
 * Emitted when a task is created, updated, deleted, or its status changes.
 * For create/update events, `task` carries the full deserialized entity.
 */
export type TaskChangedEvent = { task_id: string; change_type: TaskChangeType; task: Task | null }
/**
 * Filter options for listing tasks
 */
export type TaskFilterOptions = { 
/**
 * Filter by step names (OR semantics) - workflow step names
 */
step_names: string[] | null; 
/**
 * Filter by levels (OR semantics)
 */
levels: TaskLevel[] | null; 
/**
 * Filter by tags (OR semantics)
 */
tags: string[] | null; 
/**
 * Show only root items (no parent)
 */
root_only: boolean | null; 
/**
 * Show only children of a specific task
 */
children_of: string | null; 
/**
 * Include done items (excluded by default)
 */
include_done: boolean | null; 
/**
 * Search text in title and description
 */
search: string | null; 
/**
 * Filter by workflow_id (tasks assigned to a specific workflow)
 */
workflow_id: string | null; 
/**
 * Filter by current_step_id (tasks currently sitting at a specific step)
 */
step_id: string | null }
/**
 * Task hierarchy level - mirrors db::Level
 */
export type TaskLevel = "epic" | "ticket" | "task"
/**
 * Task priority - mirrors db::Priority
 */
export type TaskPriority = "low" | "medium" | "high" | "critical"
/**
 * Event payload for task current step changes.
 * Emitted when a task's current_step_id is updated during workflow execution.
 * Includes the new step info so frontend can update directly without refetching.
 */
export type TaskStepChangedEvent = { task_id: string; step_id: string; step_name: string }
/**
 * Options for updating a workflow step.
 * Only fields that are Some will be updated.
 * Note: agent_config is intentionally omitted — not editable from the GUI.
 */
export type UpdateStepOptions = { step_id: string; name: string | null; goal: string | null; prompt: string | null; agents: string[] | null; skills: string[] | null; step_type: StepType | null; output_schema: JsonValue | null; order: number | null; is_final: boolean | null; transitions_to: string[] | null }
/**
 * Options for updating a task - allows updating multiple fields at once
 */
export type UpdateTaskOptions = { 
/**
 * New title (if provided)
 */
title: string | null; 
/**
 * New description (if provided, null clears it)
 */
description: string | null; 
/**
 * New priority (if provided, null clears it)
 */
priority: string | null; 
/**
 * Tags to add
 */
add_tags?: string[]; 
/**
 * Tags to remove
 */
remove_tags?: string[]; 
/**
 * New task level (epic, ticket, task)
 */
level: string | null; 
/**
 * Human review flag
 */
needs_human_review: boolean | null; 
/**
 * Whether the task is archived
 */
archived: boolean | null; 
/**
 * Revision feedback text
 */
revision_feedback: string | null; 
/**
 * Worktree path (if provided, null clears it)
 */
worktree: string | null }
/**
 * Workflow - mirrors db::Workflow
 */
export type Workflow = { 
/**
 * Workflow ID (string form)
 */
id: string | null; 
/**
 * Workflow name
 */
name: string; 
/**
 * Optional description of the workflow
 */
description: string | null; 
/**
 * Reference to the initial step in the workflow
 */
initial_step: string | null; 
/**
 * Optional kanban column
 */
kanban_column: string | null; 
/**
 * Whether this is the default workflow for new tasks
 */
is_default?: boolean; 
/**
 * Additional metadata as key-value pairs
 */
metadata?: Partial<{ [key in string]: string }>; 
/**
 * Creation timestamp (ISO 8601 string)
 */
created_at: string | null; 
/**
 * Last update timestamp (ISO 8601 string)
 */
updated_at: string | null }
/**
 * The type of change that occurred on a workflow.
 */
export type WorkflowChangeType = "Created" | "Updated" | "Deleted" | 
/**
 * A task was assigned to this workflow
 */
"TaskAssigned" | 
/**
 * A task was unassigned from a workflow
 */
"TaskUnassigned"
/**
 * Event payload for workflow changes.
 * Emitted when a workflow is created, updated, or deleted.
 * For create/update events, `workflow` carries the full deserialized entity.
 */
export type WorkflowChangedEvent = { workflow_id: string; change_type: WorkflowChangeType; workflow: Workflow | null }
/**
 * Workflow transition - defines allowed transitions between workflows
 */
export type WorkflowTransition = { 
/**
 * Transition ID (string form)
 */
id: string | null; 
/**
 * Source workflow ID
 */
from_workflow_id: string; 
/**
 * Source workflow name
 */
from_workflow_name: string; 
/**
 * Target workflow ID
 */
to_workflow_id: string; 
/**
 * Target workflow name
 */
to_workflow_name: string; 
/**
 * Human-readable label for this transition
 */
label: string; 
/**
 * Optional target step ID in the destination workflow
 */
target_step_id: string | null }
/**
 * Workflow with its associated tasks including full details
 */
export type WorkflowWithTaskDetails = { 
/**
 * The workflow itself
 */
workflow: Workflow; 
/**
 * Tasks associated with this workflow
 */
tasks: Task[] }
/**
 * Workflow with its associated tasks
 */
export type WorkflowWithTasks = { 
/**
 * The workflow itself
 */
workflow: Workflow; 
/**
 * Tasks associated with this workflow
 */
tasks: Task[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
