export const V2_TOKEN_GROUPS = [
  {
    label: "Surface and text",
    tokens: [
      "--bg",
      "--bg-1",
      "--bg-2",
      "--bg-3",
      "--bg-4",
      "--fg",
      "--fg-soft",
      "--fg-mute",
      "--fg-faint",
      "--fg-ghost",
      "--line",
      "--line-strong",
    ],
  },
  {
    label: "Accent and status",
    tokens: [
      "--accent",
      "--accent-glow",
      "--accent-mute",
      "--accent-wash",
      "--ok",
      "--ok-wash",
      "--warn",
      "--warn-wash",
      "--err",
      "--err-wash",
    ],
  },
  {
    label: "Step kinds",
    tokens: [
      "--step-execute",
      "--step-execute-fg",
      "--step-execute-wash",
      "--step-eval",
      "--step-eval-fg",
      "--step-eval-wash",
      "--step-route",
      "--step-route-fg",
      "--step-route-wash",
      "--step-human",
      "--step-human-fg",
      "--step-human-wash",
      "--step-wait",
      "--step-wait-fg",
      "--step-wait-wash",
      "--step-stop",
      "--step-stop-fg",
      "--step-stop-wash",
      "--step-finish",
      "--step-finish-fg",
      "--step-finish-wash",
    ],
  },
  {
    label: "Graph edges and kind spine",
    tokens: [
      "--edge-color",
      "--edge-color-lit",
      "--edge-color-loop",
      "--edge-dash",
      "--edge-dash-loop",
      "--edge-glow",
      "--edge-glow-loop",
      "--edge-o",
      "--edge-o-dim",
      "--edge-o-loop",
      "--edge-w",
      "--edge-w-lit",
      "--kc",
      "--kf",
      "--kw",
    ],
  },
  {
    label: "Type scale",
    tokens: [
      "--text-8",
      "--text-9",
      "--text-10",
      "--text-11",
      "--text-12",
      "--text-13",
      "--text-14",
      "--text-15",
      "--text-16",
      "--text-20",
      "--text-22",
      "--text-40",
    ],
  },
  {
    label: "Type, space, radius, motion",
    tokens: [
      "--serif",
      "--sans",
      "--mono",
      "--s-0",
      "--s-1",
      "--s-1h",
      "--s-2",
      "--s-2h",
      "--s-3",
      "--s-3h",
      "--s-4",
      "--s-5",
      "--s-6",
      "--indent-1",
      "--indent-2",
      "--r-xs",
      "--r-sm",
      "--r-md",
      "--r-lg",
      "--r-full",
      "--shadow-1",
      "--shadow-2",
      "--t-fast",
      "--t-base",
      "--ease",
    ],
  },
] as const;

export const V2_TOKENS = V2_TOKEN_GROUPS.flatMap(
  (group) => group.tokens
).sort();
