//! ID generation utilities for Vertebrae services
//!
//! Provides shared ID generation logic used by both TaskService and WorkflowService.

use crate::error::{ServiceError, ServiceResult};
use sha2::{Digest, Sha256};
use std::future::Future;

/// Maximum number of collision retry attempts
const MAX_RETRIES: usize = 100;

/// Length of generated IDs (6 hex characters)
const ID_LENGTH: usize = 6;

/// Generate a unique ID from a seed string (e.g., title or name).
///
/// The ID is generated by hashing the seed and taking the first 6 hex characters.
/// If a collision is detected, random suffixes are tried until a unique ID is found.
///
/// # Arguments
///
/// * `seed` - The seed string to hash (e.g., task title or workflow name)
/// * `entity_name` - Name of the entity for error messages (e.g., "task" or "workflow")
/// * `exists_fn` - Async function that checks if an ID already exists
///
/// # Returns
///
/// A unique 6-character hexadecimal ID string.
///
/// # Errors
///
/// Returns `ServiceError::ValidationFailed` if unable to generate a unique ID
/// after maximum retries.
pub async fn generate_unique_id<F, Fut>(
    seed: &str,
    entity_name: &str,
    exists_fn: F,
) -> ServiceResult<String>
where
    F: Fn(String) -> Fut,
    Fut: Future<Output = ServiceResult<bool>>,
{
    // Generate base ID from seed hash
    let mut hasher = Sha256::new();
    hasher.update(seed.as_bytes());
    let hash = hasher.finalize();
    let base_id = hex_encode(&hash[..ID_LENGTH / 2]); // 3 bytes = 6 hex chars

    // Check for collisions
    if !exists_fn(base_id.clone()).await? {
        return Ok(base_id);
    }

    // If collision, add random suffix
    for _ in 0..MAX_RETRIES {
        use rand::Rng;
        let suffix: u16 = rand::rng().random();
        let id = format!("{}{:04x}", &base_id[..4], suffix);
        if !exists_fn(id.clone()).await? {
            return Ok(id);
        }
    }

    Err(ServiceError::validation_failed(format!(
        "Failed to generate unique {} ID after maximum retries",
        entity_name
    )))
}

/// Encode bytes as lowercase hexadecimal.
fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_generate_unique_id_no_collision() {
        let id = generate_unique_id("test seed", "test", |_| async { Ok(false) })
            .await
            .unwrap();

        assert_eq!(id.len(), ID_LENGTH);
        assert!(id.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[tokio::test]
    async fn test_generate_unique_id_with_collision_retry() {
        use std::sync::atomic::{AtomicUsize, Ordering};
        let call_count = AtomicUsize::new(0);

        let id = generate_unique_id("test seed", "test", |_| {
            let count = call_count.fetch_add(1, Ordering::SeqCst);
            async move {
                // First call (base ID) collides, subsequent calls don't
                Ok(count == 0)
            }
        })
        .await
        .unwrap();

        assert_eq!(id.len(), 8); // 4 base chars + 4 suffix chars
        assert!(id.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[tokio::test]
    async fn test_generate_unique_id_max_retries_exceeded() {
        let result = generate_unique_id("test seed", "widget", |_| async { Ok(true) }).await;

        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            err.to_string()
                .contains("Failed to generate unique widget ID")
        );
    }

    #[tokio::test]
    async fn test_hex_encode() {
        assert_eq!(hex_encode(&[0xab, 0xcd, 0xef]), "abcdef");
        assert_eq!(hex_encode(&[0x00, 0xff]), "00ff");
        assert_eq!(hex_encode(&[]), "");
    }

    #[tokio::test]
    async fn test_generate_unique_id_deterministic_base() {
        // Same seed should produce same base hash
        let id1 = generate_unique_id("same seed", "test", |_| async { Ok(false) })
            .await
            .unwrap();
        let id2 = generate_unique_id("same seed", "test", |_| async { Ok(false) })
            .await
            .unwrap();

        assert_eq!(id1, id2);
    }

    #[tokio::test]
    async fn test_generate_unique_id_different_seeds() {
        let id1 = generate_unique_id("seed one", "test", |_| async { Ok(false) })
            .await
            .unwrap();
        let id2 = generate_unique_id("seed two", "test", |_| async { Ok(false) })
            .await
            .unwrap();

        assert_ne!(id1, id2);
    }
}
