//! Orchestrator agent configuration for workflow step execution
//!
//! The orchestrator is a fixed Claude agent (using Haiku model for fast/cheap generation)
//! that analyzes task context and generates a prompt for the executor agent.
//!
//! # Role
//!
//! The orchestrator:
//! 1. Reads task details and step configuration via vtb commands
//! 2. Analyzes the current workflow step requirements
//! 3. Generates a prompt (in `result` field) for the executor agent
//!
//! # Output
//!
//! The orchestrator outputs:
//! - `result` - The prompt for the executor agent (required)
//! - `goal` - What the executor should accomplish (optional)
//! - `steps` - Concrete actions for the executor (optional)
//! - `constraints` - Rules the executor must follow (optional)
//! - `success_criteria` - How to evaluate success (optional)
//!
//! # Constraints
//!
//! - Uses Haiku model for fast, cost-effective prompt generation
//! - Uses --dangerously-skip-permissions for autonomous operation

use serde::{Deserialize, Serialize};
use vertebrae_db::AgentConfig;

/// Model to use for orchestrator agent (Haiku for fast/cheap generation)
pub const ORCHESTRATOR_MODEL: &str = "haiku";

/// Path to the orchestrator agent markdown file
pub const ORCHESTRATOR_AGENT_PATH: &str = ".claude/agents/orchestrator.md";

/// Prompt template for the orchestrator agent
///
/// Use `orchestrator_prompt()` to generate a complete prompt with task context.
pub const ORCHESTRATOR_PROMPT_TEMPLATE: &str = r#"Analyze the step {step_id}, given the task {task_id} generate a prompt for an executor agent that takes the goal of the step and the task information so that the executor agent can complete its job. You MUST NEVER do the executor job yourself, just generate the prompt. Never call 'cargo run' for 'vtb' commands, call 'vtb' directly."#;

/// The structured output from the orchestrator agent
///
/// This JSON structure is generated by the orchestrator.
/// The `result` field contains the prompt for the executor agent.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OrchestratorOutput {
    /// The generated prompt for the executor agent (required)
    pub result: String,

    /// Clear statement of what this execution should accomplish
    #[serde(default)]
    pub goal: Option<String>,

    /// Ordered list of concrete actions the execution agent should take
    #[serde(default)]
    pub steps: Vec<String>,

    /// Rules or limitations the execution agent must follow
    #[serde(default)]
    pub constraints: Vec<String>,

    /// How to determine if the execution was successful (used for evaluation)
    #[serde(default)]
    pub success_criteria: Vec<String>,
}

impl OrchestratorOutput {
    /// Create a new orchestrator output with the result prompt
    pub fn new(result: impl Into<String>) -> Self {
        Self {
            result: result.into(),
            goal: None,
            steps: Vec::new(),
            constraints: Vec::new(),
            success_criteria: Vec::new(),
        }
    }

    /// Set the goal
    pub fn with_goal(mut self, goal: impl Into<String>) -> Self {
        self.goal = Some(goal.into());
        self
    }

    /// Add a step to the execution plan
    pub fn with_step(mut self, step: impl Into<String>) -> Self {
        self.steps.push(step.into());
        self
    }

    /// Add multiple steps to the execution plan
    pub fn with_steps(mut self, steps: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.steps.extend(steps.into_iter().map(|s| s.into()));
        self
    }

    /// Add a constraint for the execution agent
    pub fn with_constraint(mut self, constraint: impl Into<String>) -> Self {
        self.constraints.push(constraint.into());
        self
    }

    /// Add multiple constraints for the execution agent
    pub fn with_constraints(
        mut self,
        constraints: impl IntoIterator<Item = impl Into<String>>,
    ) -> Self {
        self.constraints
            .extend(constraints.into_iter().map(|c| c.into()));
        self
    }

    /// Add a success criterion (used for evaluation)
    pub fn with_success_criterion(mut self, criterion: impl Into<String>) -> Self {
        self.success_criteria.push(criterion.into());
        self
    }

    /// Add multiple success criteria (used for evaluation)
    pub fn with_success_criteria(
        mut self,
        criteria: impl IntoIterator<Item = impl Into<String>>,
    ) -> Self {
        self.success_criteria
            .extend(criteria.into_iter().map(|c| c.into()));
        self
    }

    /// Serialize to JSON string
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string(self)
    }

    /// Serialize to pretty JSON string
    pub fn to_json_pretty(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    /// Parse from JSON string
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }

    /// Get the execution prompt for the executor agent
    ///
    /// Returns the `result` field which contains the generated prompt.
    pub fn to_execution_prompt(&self) -> String {
        self.result.clone()
    }
}

/// Generate a complete orchestrator prompt for a specific task and step
pub fn orchestrator_prompt(task_id: &str, step_id: &str) -> String {
    ORCHESTRATOR_PROMPT_TEMPLATE
        .replace("{task_id}", task_id)
        .replace("{step_id}", step_id)
}

/// Create an AgentConfig configured for the orchestrator
///
/// Returns an AgentConfig with:
/// - Haiku model for fast/cheap generation
/// - JSON schema for structured output
/// - Uses --dangerously-skip-permissions for autonomous operation
pub fn orchestrator_agent_config() -> AgentConfig {
    AgentConfig::new()
        .with_model(ORCHESTRATOR_MODEL)
        .with_json_schema(orchestrator_output_schema())
}

/// JSON Schema for the orchestrator output
///
/// This can be used with Claude's structured output feature to enforce
/// the output format. The `result` field is required.
pub fn orchestrator_output_schema() -> serde_json::Value {
    serde_json::json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "OrchestratorOutput",
        "type": "object",
        "required": ["result"],
        "properties": {
            "result": {
                "type": "string",
                "description": "The generated prompt for the executor agent"
            },
            "goal": {
                "type": "string",
                "description": "Clear statement of what this execution should accomplish"
            },
            "steps": {
                "type": "array",
                "description": "Ordered list of concrete actions the execution agent should take",
                "items": {
                    "type": "string"
                },
                "default": []
            },
            "constraints": {
                "type": "array",
                "description": "Rules or limitations the execution agent must follow",
                "items": {
                    "type": "string"
                },
                "default": []
            },
            "success_criteria": {
                "type": "array",
                "description": "How to determine if the execution was successful (used for evaluation)",
                "items": {
                    "type": "string"
                },
                "default": []
            }
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_orchestrator_output_serialization() {
        let output = OrchestratorOutput::new("Execute the task by following these steps...")
            .with_goal("Review the implementation")
            .with_steps(["Check security", "Verify tests"])
            .with_constraints(["Do not modify code"])
            .with_success_criteria(["All issues documented"]);

        let json = output.to_json().expect("serialization should succeed");
        let parsed = OrchestratorOutput::from_json(&json).expect("deserialization should succeed");

        assert_eq!(output, parsed);
        assert_eq!(
            parsed.result,
            "Execute the task by following these steps..."
        );
        assert_eq!(parsed.goal, Some("Review the implementation".to_string()));
        assert_eq!(parsed.steps.len(), 2);
        assert_eq!(parsed.constraints.len(), 1);
        assert_eq!(parsed.success_criteria.len(), 1);
    }

    #[test]
    fn test_orchestrator_output_defaults() {
        let output = OrchestratorOutput::new("Test prompt");

        assert_eq!(output.result, "Test prompt");
        assert!(output.goal.is_none());
        assert!(output.steps.is_empty());
        assert!(output.constraints.is_empty());
        assert!(output.success_criteria.is_empty());
    }

    #[test]
    fn test_orchestrator_output_schema_required_fields() {
        let schema = orchestrator_output_schema();
        let required = schema["required"].as_array().unwrap();
        assert!(required.contains(&serde_json::json!("result")));
    }

    #[test]
    fn test_to_execution_prompt() {
        let output = OrchestratorOutput::new("This is the executor prompt");
        let prompt = output.to_execution_prompt();
        assert_eq!(prompt, "This is the executor prompt");
    }

    #[test]
    fn test_orchestrator_agent_config() {
        let config = orchestrator_agent_config();
        assert_eq!(config.model, Some(ORCHESTRATOR_MODEL.to_string()));
        assert!(config.json_schema.is_some());
        assert!(config.system_prompt.is_none());
    }

    #[test]
    fn test_orchestrator_prompt() {
        let prompt = orchestrator_prompt("task123", "step456");

        assert!(prompt.contains("task123"));
        assert!(prompt.contains("step456"));
    }
}
