//! Orchestrator agent configuration for workflow step execution
//!
//! The orchestrator is a fixed Claude agent (using Haiku model for fast/cheap generation)
//! that analyzes task context and generates structured execution prompts.
//!
//! # Role
//!
//! The orchestrator:
//! 1. Reads task details via vtb commands (read-only)
//! 2. Analyzes the current workflow step requirements
//! 3. Generates a structured JSON prompt with goal, steps, constraints, and success criteria
//!
//! # Output
//!
//! The orchestrator outputs:
//! - `goal` - What the executor should accomplish (passed to executor)
//! - `steps` - Concrete actions for the executor (passed to executor)
//! - `constraints` - Rules the executor must follow (passed to executor)
//! - `success_criteria` - How to evaluate success (used by workflow runner, NOT passed to executor)
//!
//! # Constraints
//!
//! - Read-only: Must not mutate task state
//! - Output must be valid JSON matching [`OrchestratorOutput`]
//! - Uses Haiku model for fast, cost-effective prompt generation

use serde::{Deserialize, Serialize};
use vertebrae_db::AgentConfig;

/// Model to use for orchestrator agent (Haiku for fast/cheap generation)
pub const ORCHESTRATOR_MODEL: &str = "haiku";

/// Path to the orchestrator agent markdown file
pub const ORCHESTRATOR_AGENT_PATH: &str = ".claude/agents/orchestrator.md";

/// Tools allowed for the orchestrator agent (read-only vtb commands)
pub const ORCHESTRATOR_ALLOWED_TOOLS: &[&str] = &[
    "Bash(vtb show:*)",
    "Bash(vtb workflow show:*)",
    "Bash(vtb step show:*)",
];

/// Tools explicitly disallowed for the orchestrator agent
pub const ORCHESTRATOR_DISALLOWED_TOOLS: &[&str] = &[
    "Bash(vtb transition-to:*)",
    "Bash(vtb workflow advance:*)",
    "Bash(vtb workflow retreat:*)",
    "Bash(vtb update:*)",
    "Bash(vtb delete:*)",
    "Bash(vtb execution:*)",
    "Edit",
    "Write",
];

/// System prompt for the orchestrator agent
pub const ORCHESTRATOR_SYSTEM_PROMPT: &str = r#"You are the orchestrator agent for the Vertebrae workflow system. Your role is to analyze a task at a specific workflow step and generate a structured JSON execution prompt.

## Your Responsibilities

1. Read task details using `vtb show <task-id>`
2. Read workflow configuration using `vtb workflow show <workflow-id>`
3. Read step configuration using `vtb step show <step-id>`
4. Analyze the task context, step goal, and requirements
5. Generate a structured JSON prompt for the execution agent

## Constraints

- **Read-only**: You MUST NOT mutate task state. Only use read commands.
- **No transitions**: You do NOT advance or retreat workflow steps.
- **Focused**: Gather only the information needed to generate the prompt.

## Output Schema

Your JSON output MUST have these fields:
- goal: Clear statement of what the executor should accomplish
- steps: Array of concrete actions the executor should take
- constraints: Array of rules the executor must follow
- success_criteria: Array of conditions that indicate successful completion (used for evaluation)

## Output Format

Your final output MUST be ONLY the raw JSON object with no markdown formatting, no code blocks, no explanations. Just the JSON.

Example of correct output:
{"goal":"...","steps":[...],"constraints":[...],"success_criteria":[...]}

DO NOT wrap in ```json``` blocks. DO NOT add explanatory text. ONLY output the raw JSON."#;

/// The structured output from the orchestrator agent
///
/// This JSON structure is generated by the orchestrator:
/// - `goal`, `steps`, `constraints` are passed to the execution agent
/// - `success_criteria` is kept by the workflow runner for evaluating the result
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OrchestratorOutput {
    /// Clear statement of what this execution should accomplish
    pub goal: String,

    /// Ordered list of concrete actions the execution agent should take
    pub steps: Vec<String>,

    /// Rules or limitations the execution agent must follow
    #[serde(default)]
    pub constraints: Vec<String>,

    /// How to determine if the execution was successful (used for evaluation, not passed to executor)
    #[serde(default)]
    pub success_criteria: Vec<String>,
}

impl OrchestratorOutput {
    /// Create a new orchestrator output with required fields
    pub fn new(goal: impl Into<String>) -> Self {
        Self {
            goal: goal.into(),
            steps: Vec::new(),
            constraints: Vec::new(),
            success_criteria: Vec::new(),
        }
    }

    /// Add a step to the execution plan
    pub fn with_step(mut self, step: impl Into<String>) -> Self {
        self.steps.push(step.into());
        self
    }

    /// Add multiple steps to the execution plan
    pub fn with_steps(mut self, steps: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.steps.extend(steps.into_iter().map(|s| s.into()));
        self
    }

    /// Add a constraint for the execution agent
    pub fn with_constraint(mut self, constraint: impl Into<String>) -> Self {
        self.constraints.push(constraint.into());
        self
    }

    /// Add multiple constraints for the execution agent
    pub fn with_constraints(
        mut self,
        constraints: impl IntoIterator<Item = impl Into<String>>,
    ) -> Self {
        self.constraints
            .extend(constraints.into_iter().map(|c| c.into()));
        self
    }

    /// Add a success criterion (used for evaluation)
    pub fn with_success_criterion(mut self, criterion: impl Into<String>) -> Self {
        self.success_criteria.push(criterion.into());
        self
    }

    /// Add multiple success criteria (used for evaluation)
    pub fn with_success_criteria(
        mut self,
        criteria: impl IntoIterator<Item = impl Into<String>>,
    ) -> Self {
        self.success_criteria
            .extend(criteria.into_iter().map(|c| c.into()));
        self
    }

    /// Serialize to JSON string
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string(self)
    }

    /// Serialize to pretty JSON string
    pub fn to_json_pretty(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    /// Parse from JSON string
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }

    /// Build the execution prompt from this output (goal, steps, constraints only)
    ///
    /// This formats the orchestrator output into a prompt for the execution agent.
    /// Note: success_criteria is NOT included - it's used for evaluation, not execution.
    pub fn to_execution_prompt(&self, task_id: &str) -> String {
        let steps_formatted = self
            .steps
            .iter()
            .enumerate()
            .map(|(i, s)| format!("{}. {}", i + 1, s))
            .collect::<Vec<_>>()
            .join("\n");

        let constraints_formatted = self
            .constraints
            .iter()
            .map(|c| format!("- {}", c))
            .collect::<Vec<_>>()
            .join("\n");

        format!(
            "## Goal\n{}\n\n\
             ## Steps to Execute\n{}\n\n\
             ## Constraints\n{}\n\n\
             When complete, use `vtb workflow advance {}` to advance to the next step, \
             or `vtb workflow retreat {}` if changes are needed.",
            self.goal, steps_formatted, constraints_formatted, task_id, task_id
        )
    }
}

/// Create an AgentConfig configured for the orchestrator
///
/// Returns an AgentConfig with:
/// - Haiku model for fast/cheap generation
/// - Read-only vtb tools allowed
/// - Mutation tools disallowed
/// - Orchestrator system prompt
/// - BypassPermissions mode so vtb commands run without asking
pub fn orchestrator_agent_config() -> AgentConfig {
    AgentConfig::new()
        .with_model(ORCHESTRATOR_MODEL)
        .with_system_prompt(ORCHESTRATOR_SYSTEM_PROMPT)
        .with_permission_mode(vertebrae_db::PermissionMode::BypassPermissions)
        .with_allowed_tools(
            ORCHESTRATOR_ALLOWED_TOOLS
                .iter()
                .map(|s| s.to_string())
                .collect(),
        )
        .with_disallowed_tools(
            ORCHESTRATOR_DISALLOWED_TOOLS
                .iter()
                .map(|s| s.to_string())
                .collect(),
        )
}

/// JSON Schema for the orchestrator output
///
/// This can be used with Claude's structured output feature to enforce
/// the output format.
pub fn orchestrator_output_schema() -> serde_json::Value {
    serde_json::json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "OrchestratorOutput",
        "description": "Structured output from the orchestrator agent for workflow step execution",
        "type": "object",
        "required": ["goal", "steps"],
        "properties": {
            "goal": {
                "type": "string",
                "description": "Clear statement of what this execution should accomplish"
            },
            "steps": {
                "type": "array",
                "description": "Ordered list of concrete actions the execution agent should take",
                "items": {
                    "type": "string"
                }
            },
            "constraints": {
                "type": "array",
                "description": "Rules or limitations the execution agent must follow",
                "items": {
                    "type": "string"
                },
                "default": []
            },
            "success_criteria": {
                "type": "array",
                "description": "How to determine if the execution was successful (used for evaluation)",
                "items": {
                    "type": "string"
                },
                "default": []
            }
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_orchestrator_output_serialization() {
        let output = OrchestratorOutput::new("Review the implementation")
            .with_steps(["Check security", "Verify tests"])
            .with_constraints(["Do not modify code"])
            .with_success_criteria(["All issues documented"]);

        let json = output.to_json().expect("serialization should succeed");
        let parsed = OrchestratorOutput::from_json(&json).expect("deserialization should succeed");

        assert_eq!(output, parsed);
        assert_eq!(parsed.goal, "Review the implementation");
        assert_eq!(parsed.steps.len(), 2);
        assert_eq!(parsed.constraints.len(), 1);
        assert_eq!(parsed.success_criteria.len(), 1);
    }

    #[test]
    fn test_orchestrator_output_defaults() {
        let output = OrchestratorOutput::new("Test goal");

        assert!(output.steps.is_empty());
        assert!(output.constraints.is_empty());
        assert!(output.success_criteria.is_empty());
    }

    #[test]
    fn test_orchestrator_output_schema_required_fields() {
        let schema = orchestrator_output_schema();
        let required = schema["required"].as_array().unwrap();
        assert!(required.contains(&serde_json::json!("goal")));
        assert!(required.contains(&serde_json::json!("steps")));
    }

    #[test]
    fn test_to_execution_prompt() {
        let output = OrchestratorOutput::new("Document the function")
            .with_steps(["Read the source code", "Write summary"])
            .with_constraints(["Do not modify code"])
            .with_success_criteria(["Summary is accurate"]); // Not included in prompt

        let prompt = output.to_execution_prompt("abc123");

        assert!(prompt.contains("## Goal"));
        assert!(prompt.contains("Document the function"));
        assert!(prompt.contains("## Steps to Execute"));
        assert!(prompt.contains("1. Read the source code"));
        assert!(prompt.contains("2. Write summary"));
        assert!(prompt.contains("## Constraints"));
        assert!(prompt.contains("- Do not modify code"));
        assert!(prompt.contains("vtb workflow advance abc123"));
        // success_criteria should NOT be in the prompt
        assert!(!prompt.contains("Summary is accurate"));
    }

    #[test]
    fn test_orchestrator_agent_config() {
        let config = orchestrator_agent_config();
        assert_eq!(config.model, Some(ORCHESTRATOR_MODEL.to_string()));
        assert!(config.system_prompt.is_some());
        assert!(!config.allowed_tools.is_empty());
        assert!(!config.disallowed_tools.is_empty());
    }
}
